In [1]:
import sqlite3
import pandas as pd

**reading the table inside the database. As mentioned earlier, table name is `zipfiles`. We also know from README.txt that this table contains three columns: 'num', 'name' and 'content'.**

In [2]:
conn = sqlite3.connect('eng_subtitles_database.db')
cursor = conn.cursor()
cursor.execute("SELECT name FROM sqlite_master")
print(cursor.fetchall())

[('zipfiles',)]

In [3]:
# Printing column names
cursor.execute("PRAGMA table_info('zipfiles')")
cols = cursor.fetchall()
for i in cols:
    print(i[1])

num
name
content

In [4]:
# Loading the Database Table inside a Pandas DataFrame
data = pd.read_sql_query("""SELECT * FROM zipfiles""", conn)
data.head()

,num,name,content
0,9180533,the.message.(1976).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x1c\xa9\x...
1,9180583,here.comes.the.grump.s01.e09.joltin.jack.in.bo...,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x17\xb9\x...
2,9180592,yumis.cells.s02.e13.episode.2.13.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00L\xb9\x99V...
3,9180594,yumis.cells.s02.e14.episode.2.14.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00U\xa9\x99V...
4,9180600,broker.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x001\xa9\x99V...

In [5]:
data.shape

(82498, 3)

In [17]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 82498 entries, 0 to 82497
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   num      82498 non-null  int64
 1   name     82498 non-null  str
 2   content  82498 non-null  object
dtypes: int64(1), object(1), str(1)
memory usage: 1.9+ MB

In [ ]:
# Check duplicated data
data.duplicated().sum()

np.int64(0)

In [ ]:
# Check null values
data.isna().sum()

num        0
name       0
content    0
dtype: int64

In [26]:
data.iloc[0]

num                                                  9180533
name                              the.message.(1976).eng.1cd
content    b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x1c\xa9\x...
Name: 0, dtype: object

In [5]:
data.iloc[0]['content']

b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x1c\xa9\x99V\x9fx\x96\xf0\x8c\x9e\x00\x00\x86\x9b\x01\x00;\x00\x00\x00The.Message.1976.REMASTERED.1080p.BluRay.x264-PiGNUS.EN.srt\xad\xbdm\x93\xdc\xc6\x91.\xfa\x9d\x11\xfc\x0f-}\xe1=\x11-\x9d\x06P\x85\x17\x9d\x8d\xd5%%[\xa4-Y>&u\x15>\xdf\xd0\xd3\x98\x19x\xfae\x0cts<\xfe\xf57\x9f\'\xb3\n\xd9\xa4\xbc\xbb\xf7\xc6Fl\xacELW\xa2\xaa\x90\x95\x95\xafO\x16/_l6\xdf\xe0\xff\xea\xf5f\xb3Y}\xf5\xd5\xbf\xaf\xf4AQ\xae7Mx\xf9\xe2\xd7\xfe|s\xbf\xea\x8f\xcf\xab\x8f\xe3n8\xadN\xc7\xfdx\x1cVO\xe3\xf9~\xf5\xf3\xe3p\xfc\xea\xfd/o>\xbc\xfb\xf0\xe3\xef\xde\xbf|\xf1\xfbi\x18Vo\xa6\xd3\xd3<L\xab\xe1\x1f\xe7\xe18\x8f\xa7\xe37\xab\xd3\xbc\xdb~-\xc3\x1e\xfe\xa7<|\xf9\xe2\xe5\x8bR_[~S\xd6\xeb\xa2k\xf3k\xe5A\xb7\xeeb\xf5\xf2\xc5\xbb\xe3\xea|?\xac\x8e\xfdaX\x9dnW?\x9cvk>8\x9c\xe6\xf3\xean\xeao\xc6\xd3ev\x8f~\x1a\xa6\x9b\xf1\xf6\xb2\xff\x1a\xe4\xabD\xbe*d\x11\xa5#_U\xeb\xaa\xd9`\xa6\xa7\xc3\xea\xa7\xcb}\x7f8\xf4F\xf9\xa7a\x9e\x87\xe3\x9d\xcc\\\xdf\x07B!\x13\xaa\xd61n<!\xd9\xaf\xd0\xbc|q>\xad\xde\x0e2\x9d\xfd\x98\xa63\x1c\x1e\x87\xe9D*o\x9e\xff\xd9\x1f\xcf\xe3\xe5\xc0Y\xc5L\xac^\x87M\xe3\x89u\xebP\xcb\xbb\xeed\xff\xce\xe3\xf1n^\t\xd9\xfb\xf1\xb0z\xba?\xad\xc6\x19d_\xbe\xb8=\xed\xf7\xa7\'\x9d\xde4\xde\xdd\x9f\x07\xd9\x81\xd5\xdde\xdc\xf5\xc7\x9b\x81o\xa8\xf3\x1b\xbau\xd3V\xee\r\xa1\\\xc7\xae\x90m]m\xc7\xdd\xea\xf9t\xe1\x1b\x86~\xe2\x94w\xe3G|\xd3\x9b~\xaf\xfb\xd7$:\xa1Z\x17\xb5_v\x88\xeb\xb6h@\xa7?\xe8\xe6\x7f\xb2k\xa0\x8b\xe7\x8f\xc3\xe9q?\xfc/Pk3\xb5z]U~\xdd\xa1\x95i\xca\xba\xfb\x9b\x9b\xe1\xf1\xbcz7\xef\x85\xea\xad\xec\x9dLpZ\xcd\xfd\xfec\x7f\x16\x06\xe2\x9c\xbaD%\x96\xeb\xb2*\x1c\x95\x18\xd6\xcdF\xfe\xfcvX\xcd\x8fC\xff0c*\xfd\xea8<\xad\x1e\xa7\xd3\xe3\xfdp^\x8d\xc7\xd5\xeb\xa9\xdf\x8e=I\x15\x9bL+\xae7\xb5g\xbf\xd8\xac\xdb2\x82\xeb\xe7\xd5x^\xed\xc7\x87A\x96#\x9f\xe0\xe9~8\xae\xfep\xba?\xeaG~\xd3?\x9e\xc7Yx\xf9\x06\x0c*k~\x90\xcf\x06NP\xbe)\x8a\xfc\x86v]\x84\x98\xdfP}\xb3)\xd6e#\xfc\x7f\xba\x9c1On\xff \xe7\xe5\xbc^\xddL\xcf\xa0\xd2o\xf1\xb7\xbc\xfaoI\xd0NL\xc5\x13S\xd5\x8e`\xd9\xae\xbb\x8dp\xfc\x87\x930\xf4\xdf\xfb\xa7\xbf\x8f\xc2\x88\x7f\xee\xcf\xd3\xd8Orr\xe5\x1d\xaf\xf7\xc3?\xfa\xe3nJ\xcb\xaf\x12-\xe1\x8a\xe0\x0e\xbd<\x08\xeb\xba\x92\xef\xf5\xc7q\x9e\xfa\xb5g\xe5?\x0f\xd3\x9c\xc6\x87<^v>6~|\xb3\x0e\x9dl_:Yd\xa9\x99\xfcF\x81\x81\xd5\xe2\x911\x8b\x92\x8b\x99\\\xb3n\x8a\xe0\xc8\xc5\x8d\x9c:\xd9\xca\xd7\xff\t\x7f|\xad\x84\xeaDH\xc6\xb5\x9d_\x97\xf0L\x08\xc2"\xc3a+guPJ:\xa8\xc9\x83\xc2\xba\xac\xfdb\xe4\xd35\xa5\xec\xfb_e\xf67\'\xc8\xa1\xcf>\xd9\xcb\x17\xf3a\xd8\xef\xf1\xd5\xe4\x0f\xe0\x85\xbd\x88\xca\xdd\xea\xee\xd4\x9f\x95|\x9b\xc9\x83\xd7\x17Q\x14D\xc6\xcaQ\xda\xf0\xbb\x9d\x85\x86\xed0\x18m\x1a\xe4h\xae\xe6\xfb\xd3e\xbf[=\x1c\x87a\xaf<`G@\x86vr\x90<\xad\xa2X\xd7\x9b\xcd\xb2\xef\xeb\xcf\xa4\x19gSn\x12\x85\xa2Z\xd7\xa1\xf5\x14\xe2\xba\xda\xc8\x06\xfe*\x12\xe7\xae\xff8P\xfc\x90\xf3\xfb\xcb\xf9\xfe4\x8d\xe7gN\xa2,2\x89(\x0b\x8a\x9e\x84\xac0\xc8~A\n\xc8\xbb\xcfY\xbe\xca\x01\x172"*\xa6\x9bg\x9c\x95C\x7f\x94\xe3bS2\xc6\x8e\x98R\xe5\x98)~SF9)\xc2k\x1fd3\xde\xdf\xdc\x9f\xf6\xfd4sw\xdf\xca\xc9\x93\x19\xf5G\x9et\xe5\x8a\xaf\xf4w\xbf\x1c\xc7\x8f\xd8\xc7\xf3\xb32\xfeW\xaf\xffy/BN\xce\xffw\xfd8\x9d\xf4GoEz\xea\xb0\xf1f\xf5\xdd\xe9(bw\x9e\xd3\x97}\x7f?\xf6\x14\x18?\x0e\xdb\xfex:r\x92U\x9a$N\xdf\xa6r\x93\x94\x8b\xa1\tQ\xe9\x1e\xfa\x07y\xb7\x12\x92\x8d\xbb\x1d\xf7\x87\xd5\xfd\xe9\x08^\x05\xe5\xf4\xc6\xf3\xd4\xefF\xf0\xed\xcb\x17O\xf7\xa3\x1cQY\xda\x0eB^\xde\xcb\xdf\xe1\xd4\xcd\xa7#y;M\xeb\xcf*\xc9Dn\xdc\xde\x0eG\xf9y\x7f\xd7\x8f\xc7YG\xcc\x8f\xa3|\xa0K\xbf\xb7u\xe3\xed\x10\xcc\xfd\x9d\xde\x0beH\xf3\xc7t\xddG\x8b\x10\xe8U\xab\x9b<\rr\xb4\x86\xb5\x89o\xcc\x00\xb4~:\xa5\x8f\xf84\n\x97\x1eO\xe7\xd5\x96\xcc\xf9\xa4r\xb9\x8c\x89\xb6\x9c\xba\xcd\xa6s\xb4c%w\xa4\xf0\xd4\xbf\x8d\xff.\xdc\xb9z\x1e\xf8\x01o\xcf\xc2\x94\xdf\xddO\xf2\x11\xe5\xe2\x19v\xeb\x7f\xfb\x9f\xe3\xbf\x93R\x9d)U\xeb2\xd4\x9eRT\xd6\x12J\x14\xc4\xbf\xbb\xc8v\x88\x12"|5_\x8e\x0f\xf8\\<\x95\xfd\xf4 \x1b3\xcc\x99d\x93I\xca\xc5\xb5)=\xc9v]7\x1dI\x82\xa7\x06a\x9bg={\xa0$_Dd\xbb\\\x8b\xfb\xf1\x9f\xfc\x0er\x03\xe0o\xb7=O\xfb2\xe76\xbf@\xb8\xbfYV_\x8b\xf0\x17~\xd6\xd5gq\x88\toO\x93|y\x99\xf1O\xc3\xcd\x8d\x08\xd9\xe5n\xcaD\xed\xa0\x93F\xd7DO\xb4Y\x17\x90\x88 \x8a\xe1\xa4x\xc6\x96\xf4\xa2\x14\x08/\x91\xb9\x8ew\x98\xfc\xf9y\xbd\x9a.\xfba\xb7\xda>\xcbe6\xf3\x00\xde\x8bB\x92\xb7\xa7\xda\xe4\x1752\xd9\xc2\xbd\xa8\xd8\xac\xeb\xb6\xb1\x1d?\xcd\xb2\xd7C\xbf\x17\t\x8e\xf7\x1d.\xfb\xf3\xf8\xb8\x97o\xf7\xf2\x85\x90\xeeW\x97\xe3\xf8\xf7\x8b0\xcd\x84\r\x1b\x84\xe9\xbe\xcek\xa9\x8a\xf4\n\xa1\xd89\xad\xa7\x86\x86Y\xe3\xe8\xc8+d\x05\xcfr\x0c.\xb3L\x16\xdb\x7fw\xda\xcd\x0b\x892\x93\x10u\xa4\xf4\xdbQ@kU\xbe\xf8\x1d> yl\xbd\xd2\x83$\xca\xd9\xa8\xda#IN\x83<\xbe\x15)\x90?^Ue\xc2\xb50\\\xe9\t\xb7r\x91m\xd2\xdcL\xdcc\x81\xc3,\x1b\xb9\x9dN\x17Q\xc0@w\x14\xe1\xb2;\xed\x97-\r\x99f\xbb\x8e\xeer\xad\xbf)EH\xb7u\xe68\xd0\x1d\x0f\xe0V\x9b\xa2\x90\xc2\xba\xc1\x1b\xa6D\xdd\\D\xd0\xed\x9e\xd3\x12\xfe\xd8\xf7\xdb\x85K\xaa\x98\xde$\xc7\xa5\xae+\xf7\xa6X\xaf\xeb\xa8\xb3\xffYtC\xa7&\x8b\xa8y\x96\xc3;A\xdd\x83\x80\x94\xebPXs\xd9\x91:\xd3\xac\xd7m\xedg\x1f;\xb9b\x9a\xbc#\x9c\xcb\xea^x\xfaxz\x126\x18xC\xf6\xfa\x11A\x1a\xbbr:O\xcf\x99t\x93Iw\xeb\xd6\t\xfaF\xee\x0e\x91A\x15I\x0b\xabA\x01\x16\xa2\xab\xdb\x01\xca\xaeH\xc5#\xe6\xb5\x11Y!\x92o\xc2\xbdr\xcd\x1dv\x02\x85\x8c\x08\x89\xb2\xf0tE\xadn\x1awX\xe4\xa8\xd5\xc5f\xf5\xfa\xeb\xef\x97\xe1]\x1a\x1e\xa04D7<\x14\xa2\xdd\xc8\xe7|3\xee\xfb\xfd\x174\x076\xe9\xc7\xd00Z\xffc\xd10"\xae\x89\xb7\xb8;\xa1\xef`k\xe4\xe3\xf5\xcf\xaff\xd1\x1e.2\xed_\x0e\xfds\xcfK4\x14\x99\x8e\x9c\x81\xb2\xf2t*\xdd\x8b?\x89\x9c}\x1e\xce\xa6\xda\x842\x0f\xa8\xd6]Y\xfa\x015Tt\xf9\x02\x97\xb3^;\xcfI\xab\x97{X\xc4\xed\x84\xd3\xb4\xd7\xcb6T\x99\x8c\xa8\xe2\xee\xf3\xb6\xd0F\xaa\x9a\xf7\xbf\xc8\x12\xcc\xff\xf1rvT\x84_\xed\x06\x92E\xdd\r\xf2\x87I\x94\x1f\xfcN\xee\xda\x15\x8f\xde\xe34\x9c\xe5\xfa\xd9\x0e\xe7\xa7Ah\xdc\x1f\x0e\xbaV;\x10|EW\x07\xff\xceJv\x1c\xea\x9dP?\x9c&=\xf6P\x10\x1e\xf7P\xd2L\xa8+\xd7\x93T\xcc\xa4\xbau\xd1\xd4\x8e\x94\x08\x97\n\x8a\xe7w\xfd\xd4\x7f\xec\x8f\xab[\xd8w\xef\x9f\x93\xca\x1b\xea4\x12f\xad\xdb\xf0\x16G\xbfi\x85\x87\xbeZ\xbd=\x1cd\xbb)\x8a\x0e\x17\x9c\x15|\xca-\xd62]\x8eG\xe1\xca\xaf\xf1+\xb9(\x9f_\xc9E\xb8\xa5a0\xcd\xe7g}C\x93\xdf \x04\x9dI\xdbB\x10\xd4\xd0M\xff,;z+\xea\x89\xae\xf5 t\xe5\x86=\x9e&HUQ\x00g\xa5\xd3f:\xb2\xc6\xce\xafQ\xe4G \x8b\x9d\x9e\xa0B\xe1\x1c\x0f\xc3\xa3\xfc\x7f\xb9\x93`\x91q\xbe4Edz\xd0\x92e)\xf6\r\xbaD\x942\xc8/\xbf\x94[\xaa\x13\xa2\xcd\x86\xbf\x8c\x9b\xfcK\xd8\x06\xa5\xffe\xb5\x0e\xb8z~\xc0\x12@\x1a\xa7\xfd"f\xc5\xa0\xcc\x15\x8b<T\x8c\xe5\xa6\xf0C\xe3\xba\xc3A\xd3S\xc8\xcd}\xc0\xd4\x85\x8b^\xbe\xa0\x89\x8f\xe9\xca\xd9\x7f\x1c\xcfTb\x94`\x99\t\xb6\xeb\x8d3\x1c[x\t\x9a:*\xe7\x9ce#E\xb1\xda\xcei\xcd\xab\xfd\xd0\xefD\x7fQ"U"R\xe1\x82\xf6\xfb\x99l\xe27r3\xec\xc8\xe2O\xfd\x99|\xbd3\x1b\xf64\x88\xb0\xe7\xb6\x1a/\xbe\xed\x1f\xc6\x83\x1chJ9\xdd\xb0\xcc\xdeb+o*\xbfj\x18CA\x8f\x94|o\xa8\xa5\x03\xdf"F)\xfek\x92\x0b\xea\x08;^$2\x0f\xdbi%\n"\xee\x95a\xd2\xa9gv\x17i\x13j\xff\xd5 \xf1q=\xc9\xfa\x85e\xd3m\xb2\xc5B\xd6\xabw\xab\xf9iP\xa5\x17\xe7tX\x93X>\x012\xb6\xd9\xf8\xa3O\xd5H\xd8\x8e\x8e\x86\xf1x4\xa9K\x92\xdc\x11\xca\xbe\x98\x19\\l\xe4f\xb3ld\x07\x93\xb6\xc0>\xff|/\x93\x11\xbd\xechJi\x8f\xab\xe7\x93\x7f\xab\xd0\xd8\x9f>\x9a\xa6\x8c=\x9e\x9eu\x8a\xc6\xfa$X\xc6\xca\xbf!\x8a\xd1\xdb\xd1\xdb\xf2z{Y\xbd\xbf\xdc\x8a\xf6\xbf^A#\xa5\xc5\x8co\x07U\xda\xc4e\xec2%\xe1<g\xe7tPt\x1a\xc8\xb9G1\x90\x17\xed\xba\x9f\xce\xca.\xf5&\x8f\x94S\xeb\xae\x83\x0e\x92\xa3\x80\x1c\xa6\x84\xe4,N\xb7\xcf\xb2M\xe3\xf1\xe3x\x1e\xe6\xcc1\xf2\x80\xcb\xa9\x8bDJF\x96\xce\x0b\xd5Qm\xc1j\xf5\xd2\xff\xdb\xe9\x19N\x9e\x07\x11\xa4X\x08\xf6F\xff\xad\nv]f:\xf5:\xbac\xd0A\xb2T\x10\x8a\xcaaOr\xa9\xab\xa8\xbe\x11Cd\xa6\x1f\xe1\xb8\xd3\xb9T\x99\x86(6\x95_V\xb9\x11\x9d*p.\xab\x19\xa2cV\xc5 \xadO\xe7\x10\xd2x\x11 e\xe1?\x8d\x1c\xf6\xae\x05+\x8a\xd0\x99D\x8b\xde\xeb\x14`\xe4\x8b\x05q\'\xca\xd2p\x97v$f*a\xbdq\x06z\x87\x13^l"\x0c\xa2\xfftsuBu"\x85c\xd7xRb\xd1tPT\xe8\xe2\xe3\xaa\xc6\xfd\xc3\xd3i:pa\xdf\t\x87\x8b\xd2}x\x16\x99\xb1S9S7\x99\x96lp\xeb9;\xc8\x06\xe3\x84\xbf\x96+i\xe8\xe7\xcb4$\xff\xd6~<l\x8d\xdb\xea\xcc\xb7\xf2\xf3\xb6\rn<ns\xf0-wdNo\x95\xefs\x14\x0b\x19\x87A\xb4\xf6\xfe\xe38\xdf\'\xb2\xc3\xb3y\xf22\x07GH\x11\xff\xc1D}\x8ap\xe1\xfcu\x98\xd7\xabF\x84\xdd\xf1\xee|\xaf\xdc\xdbd\xee\xc5\x8fB\xfeL\xc5\x06\x97o\r\'R\tE\xea\xd8\x9btl\x94G\xf5\xef]Q\xfa\x01"\xffa\x1f,\x1fC\xe4\xde\xd3x\xabb\xaf)\xf3\xc0\xb0\x0em\xeb\x07F\x19\xd8\xc0\xaf\xa3\xaf\xa8\xd2/)\xc5\x83\xfbeU\x8a\x82\xd5An\xac\xa9\xa3|\x81\xcbU\x95\x00=\x97/_$5S\xaf\x1c9,\xc7a\xd8\xcd\xe4\xa6&$\xc2\xa0\xb3\x98^x@WN:_\x97G\\6\xb6\xe0\x98\x06\t\xdf\xb4\xc1\xcf[>^\x81\x9b\xf0\xd7\xe4s\x15sA\xaeY\xfa`E\r?\xed\xb24\xc5\x93\xfd\xe9\xf4 \xc6\nUu\xf9\xac\xf3\xe9\xa2N\x9a\xa6N/\x10\xa1]/*\x16\x1e\xc8\x8e\xc2^\x14\x1dE\xd4%h\xcbO\xfd\xb3j* \xac\xf3k\xf2pa=\xf7A\n|\xa1\x12\xd6\xd4\xaf\xf7\xa6\x9f,N6\xa8\xde;1\xc8IG\xa7\xa1<\xa9\xc3b\xb1\xf1t\x8au\x87]\x07\x9d\xdd\xe9\xf8\xeaLuOV\xf8\x08\x9f\x8f\x8e\xee\xf2hQ\x97\xea\xce\x8f\x96\xe3\xd6\xb5t\xb6\x8e\xb3\xfa\xe1\x8e\x83\xe8\x85O\x9c~\xbb\xc9\x03\xe1hh\xfc\xc0 rB6\xe7\xa7\xfeyK\xff\x16\xdd\t\xb0G\xcdI\xd1\x16yl\x84\xdf\xc0\x8f\x15\x1d\x17n\xc2\xef\xf8kN\xb1-\xf3\xafk\xd9\xd6\xe0\x7f\r\x11W\xa6)\x86\xe4xHJp[\xe5\x91b\x88l\n7\xb2\x90\x8b\x0cn\xb4wg\xe1u\xd1\xf9\xfa\xf3e\xea\xf7v\xcc\xdb\x90\xc6\xc9\xcfB\xe17\xa5\x90\xb5\xc1t\xa2\x8f\xd3\x0cq\x1c\x955\xd6y\x037\x9e\x9c\xf4[QO\xec\x9e\x16#\x92\xae\x15\xa8CJ;f\xda\xb2\xf6\xce\xaf\xbdh\xe4\xe0\xf2\xb8\x9fI\xed\xfe$\xda\x03\xb5dh\xde\xf3=\xfc]\xb8\x03G\xb8\x00n\xe4\xa0(\xc1:\x13l\xbd\xc2\x8b\x070\xe4\x10\n8c{\xf2*y\xc9\xb7M\x1e\x06\r\xcb\xef\x8d\xc8y:\x04~/JV\x9f\x0f\xc6N\xd4\x18L\xe6\xe5\x8bi\x9c\x1f\xf4.M^\xc7\xd7\xfb\xaf~\xf9\xe7?{\x1e\xd66\xf3#\xee\x8b\xca3\x86(\x87\x05\xa6\x0br<\xa8+0\xd5=\xdd\r\xba\x96\xcc\x8d%,\xbc\xe8\xc7\x9a\xcb\xf1\xa7^V\xb1N\xae\x03\xbc\x1c4\xa0h=\x0eS\xd2\'\xbb\xcc\x9c\xa2>\xfa\xa3Y\xc0-VBC\x92K\xecs:/_\xdc\xf6\x87Q\xb44\xeaY\xd3(\x9fO\xe9e\x86\xadp\x07\xfa\x8fVE9\xbcA\xe5\xfe\xdb\xcb6\xf3P\x97\xb9V~\x11+\xcf\xb5b~n\xe0\x0e\xe6\xcf\xd7&u\xa0\x97p)7j\xd7\xccJRL\xad\xddxc\x7f\xba\x15\x15M\x89g\xc6\x16Ze\xe3\x194\x041\x12k\xfa\x9ao`.\xc03\x9c\x1d-t\xcd\x0b\xfb\xe0\x94\xdc\x9f\xe8b\\\xfe&,\xb2\xe3\x17\x15\x8dW\xdf\x92\x8f\x81\x10-[\xff5\xe4\xe6-\xa0\x8e\xfcr\x14E\x14\x0e\xcc\xed\xdef\x96\xd9\x1b?\x89Wc\x84\xbd\xf1\x05\xff2l\xe1HgPo\xbb\xefg\x11)\x87\xfc\xca\xcc\xcc\x90\xd1WB\x11\xc1 \\\xf6\xbc\x0c\xdf\xbd\x12\x9b\xe4v\xea\xc7\x9ds=S\xcc\xdc\xf7\xd3\x01\xd2m\x1e\xf6\xb7J\xd2\x18\xbd\xa4\xd7`\xb9\xb3\xf1\x00<UX\x88\xab\xdf\x8b\x8c\x9eW3)\xdd\x9b&\xbb\xb8\x92\xb0=Pe\x95f\x9bh\x8a5\x1a\xdc\xfe\x97\xd4\x1d#\xc3f\x07h\xfc\xf4\xa2\x8a\x02\xa0!\xce\xe1\x1f"\r\x8e\xb6S]\xa6\xd1\xc8\xb1(<\x8dNoK\\\xc8\x1f\xc4J\xda~\xb1Z\xfeS\xc3Z\x9b4\x18f^\xd9\xb8\xc1%\x9c\xeb\xb4\x8f\x11\xcd\xa5\xd8\x86\xb5p\x96\x9b\xf7\xff\xc8~\xd9\xf8"\x8f\xc7\xe5\x18\xfd\xf8(B\x83\xee\x8d\xf97\xee\x1d9!\x8c\xa7\xd2\xcd\xf1v\x9cz\xb8.4f\xb1)3\xcdZ4\xc7\xd2\xd3\x14\xcd\x06J\xf2\xdb\xe1\xd5\xacv\xf6\xe5Q\xefX\xf9\xff\x88$\xefd\xeb-`We*\x88vm\x1c\x15\xb9\xfc\x0b\xa8\x1b\x7f:\xade[a\xfd@[\xc0\xb56\xd3\r1Z\x9cg\x13\x12\x89\nAM\xbf8\x9cE\x88\xd8?\xde\xf7\xbb\xf1o=\x1c\xf2\x8fr\xb7\xc3g\xc6\xaf\x05\x82/_p\xb5"vq[\x9e\x8e\xf4\xb1\xe3\xfe\xbe\x97\xc7\xf6\x86\x98\xdf \xdf\xae\xf3\xdf\xaejU\x99\xfa\x00\x16\xba\xc7z\xe73\xf82-\xd8\x08\xd4\x89\x80\x1c\xe0\xc2)\'%|Q\x1b\xe8\x99\x1f>\xdd\x98\xcc\xc7\x01.\xf2\xca\x0fiL\xce/\xa7\x82V\xf6x\xc0\xf4\xd5#(\xdf\xab7\xe5\xbc\xd8d\xf6\x95S\x16K\xbf\xc7\xa1\x13\xee\xe9\xe8\xe5\xeb\xc5\xf0M\xf1\xb6MfV\x18\xa8\xad\x9f\xaf\x9c\xcbMG\x86W\x15\xe3\xe1xz\x12\x99\x86\xc8\x8ahU\x83H2%Qd\x96E\x14\xb7\xf0\xf3\x17\x05\xa8,:\xf3\xde\x1d\xf3q\x11M~\x0f\xcf\xda\x89N\x13\xe3\xbc>\xaf%;\xf6\n\x8b\xc1\x16\x15\xb2\x00\xba%d\x8a\x07r\xc9BCH\x9c\xfc\xc5\xea/b9\xeb!\xb0H+~U\xaf\xebj\xe3\x86\xc9W\xe9\x10\xa4\xf8$7\xe1,\x8a\xd4\x8f\xb8\xdb!\xb3op\xaa\xe0\x18?$/\xd4[a\x94\x19\x99\x10g8Nv\x93\xe8Y2h+\n\xa4\xc5?-\x1e[0\x1e[.\x1e\xb2B\x03\xace\xa9:\xe9y\xe8o\xee\xe5\xb2\xd5\xab\xb7\xa76\x80m\x9d!M\x8cR\xc8\x94\xe0\x18/<\xa5Z\xf6`\x039\x9b\x17j\xec\x1ap2;\xa7\xcf\x04\x1e2\x84N\xde.\x9cz\x9e\x86\xc3\x96\xc6\xb6\xd8\x94\x83\xfaYDN\x1f\x1f\xb2\x8f\xb2\xb0\xf8\xab\x8c\xaf\x10\xda\x8c\x8e\xa0\x1c\xd2\r<\x04pR\xca\xc0{\xc4m\x1eE\x81>\xda\xc8&\x8f,ed\xe5G\xd6\xeb\n\xf1\x10J\xa9\xd5\xaf\\w\xff\xf88\x1c\x11)\x10\xb5Cto\xd5??ej\x15?\x16\x7f\x05!Q\xf6\xdc\x1d\x1d\xe8\xde\x85\xe1\xfbV\xe3H\xfd^d\xf0:9z\xb2"UX\xd4\x15\x03\xa2\x08\xc5\x8d\xa7 \xe7\x04R\xfd\xfde\xb7\x1b\x8e\xfb\xe7\xb5h\x08T\x7f\xf6\x0c\x05\x93\xd6i\x91@\x16}\x95\x810\r\x82\xdf\x1f\xb1\x13\x03$\xe5\x07\xd3\x9f\xc4v\x96\xf5~\xe3\xd8\xd2\xe2\xae\xf8\xad\xd8\xb7\x9d\x9fF\x843\xd4\x07\xdd\xa7\x81\xc1\x99oD\x16\xc2\xd2\xc4e\x03\xcf\x90\xcd\xc2\xf8;\xc2\x10\xd8,\xb1L<\x08\xebj\xb3\xf1\xb3\x10\x99\'\xec\xb6\x93\xbdf\xb8\xf1jBU\xa6#wz\xd7y:\xb5\x1a:\xff\xe2\x9c\xa8\xb8\xb1\x98$~\xde\x88\xb2\xd4\xb8\xf1\x05T\xa1\xa0\x1a\xa1\x9d\xa7U:N\xf2\xbd\xfe\xf5y2\xca1Q\x86>_\xf9\x15"\xc6\x0c\x99\xf8\xf4_;O\x16\x91\xc4@\xd9\x1a\'\x0b"\xf4\xf4\x12|\xe96\xa4\xc9?\x16i_\xd4\xee\xc7\xa5|o\x04\x86p\x8c\xf5\x15\xe3-\x04!\xf8\xee\x87~;\x8d)\xc2o\xe1D\x0c\xa9\xae\x0ep\x84\xcb$4\xb4M\xd4\xa2p\xee\xe9^vaH\xf9\x0c\x16<,\x18\xabn\x9cP\x8e\xcc\x86\x8a\x95y\xb0\xaeb\x92\xf2\x9dq\xb4u\x83\xaf\xae\x06f"\xf4Oi\x9ap\xcd\x8f\xc2\xea\x96H\xb2I\xef\x12\xd2\xa1\xf3;-\x97l\r\tl<0\xcb\xa1\x1d4/\xe7\x80\x80\x8e\xa8\xb6\xc7\x1d\xd3&\xf4\xef\xc80\xf8\xa7e\xfa\x14\x163\x04\x95\x80\x1c\tO\x16\x16@g\x1e/Q\xbc0=5\xc5\xf5\xdbW\x99\xbb\x91dU_\xad\xbe\x95\xe3+\x1f\xf4\xf2(\xefd\xb8w%\x86\x0f\\\x80/_\xe02\xbf\x87\x17\xd8V\x9b\xcfl\x95\xb9\x1c\xc2\xbf.\x1d=\x11\xd6uc\xd1\x8b\xb4;8\xb5)w\x8b\'\xc6f\x95y\x1d:\xf3\xc6\x9f\x15\xc8\xe52%T\x19\x99$P\xab\xcc\xc8r\x01\x8b\x02\xe3\x86!3\x06\xfa>\xac\x01($9\xf1C\x07f\xbe\xbdN\x96*\x18Zo\xe1\xe4\xef-\xd0\xfd\x9by"E\x95y\x19a\xbfnysM\xdflmW\x12\xe4\xf8=\x94"aG\xcdZB\x04JY\xd9\xe2r\x05\x83\xd8\xb5\xd3dk\xf8\x06\xa8\r\xe1$\xd3L\xd6\x01]\x1e \x87\xcd\xddG\xb5\xba\x7f[]\xed\xeb\xfd\xa8\xbf\xb7`\\\xc1\xe0\xf5f\xf1\xec\xe3A\xa7\x91;\xf9\xfd\x9a\x8a\xda\xadl+\xc6\x8a\xbe\xfc\xa6\x7f\x98,\x8d\xa9H\x04\n\xf8H*G@\x04G\x05\x0f\xc3k\xdd^]\x91\x05\xe1\nF\xae\xcb\xce\xafH\xc4\xc3\x06l\xc9\xaf\xc8\xa4\x99\xdd\xe9\x11bkN<m\xa1\xb7\x82\xb1\xe6\xe8ts\x06\x8aK\\\xc6op\xedL\xc3\xede\x0f\x16\x12\x11u\xd0D\xbd~\xff`4B\xa2Q\xc2\x17\xbdq4p\x85\xc3\xbd\xfa\x01\x99D\xe0\xbe{\xda\xf67\xfb\x81Z\x89X\xc2\xe7\xe1\x06\x13\x92\xbf\x99%so\xf7\x9eX\x84\xe3~\xa7\xce\xf4\xf4C\x92\xe0\xc5oo\x8e\xf9\xcd\x8dlm\xf4o\x96K\x106\xe1k\xe6u \x83\xd0\xb8\xd7bn\xf2\x13\x11\x0e.\xb9\x00\x0f \xdc:J\x9ag93\xcf)\xd0\xa8\xf9&\xf30+\x81&\x13\x90\xdf_1\x84\x88\x81\x12<J%"\x1d8K\xcf\xeaW[9\xd6\x90-\xdb\xcb|os\xc9\xcc(\xa7vs\xb5s\x01r\x15\x97\xd5-w{w\xb2\xfbr>\x8b\xca|d\xb8"\xb9\xb84\xd1\xe2I]WF83\xad\xd0i\xab\xd6\x13n\xc4\x08\x8f\xa6D!\xc3\x92\xf2\x8e\xca\x05R3D\xe8\x88\xc1}\xcey<\x0c)YB\\\xe6l\xe8\xf0\x9d\xdfm9\xf7ES\xfe\x16\xd1;Q\x89&MU\x11[\x05\x9f4\x93~\xec\x1167\xda\x99\xe9#n\x03\xffUDV4\xa5]\xff\xb2j\xc4U&8\xba\xe7\xf3\xc0\xed\xf4\xbaL\xccg\x01\x02\xa5\xf5\xeb\x16\xfd\xa4,\xa8<\xae\xfa\xb3l"\xfc\x14\xe7D\xd2F\xe7\xc3\x00\xef\xb6\xb3\xc5\x1a*%\xb87~e\x84\x8c\x991p\xf7\xca\xa6\x9f\xb6\xc2,\xe6\xf0\xb8O\xe1\xbd\xc2\xe2o6\xd2y\xac\x1auU\xc2\xbd\x0c\xff\t6Dv\x01\n\x91\xa501-\x8b:@\xa6\x153\xad\xe0\x03\x8ex\x00/\\\xd0\xd8+t*\x99\x8f%\xad\xe6\xb4-\xdekO\x08\xec\x9e\x93\x16)<4\x0c\x88\xe3\xcb\x16Nb\xb4\xe9[\xea\xfc\x16\x9c\xa5\xe0\xde\x82\x14\x19|\x01\xbc\x01IV\xb08\xe5X\xc8\xa7^\x82\xefBF\xc5\x91\x05\xe40\xac\xf0i\x9cx`\xfe\xef\xefq\xa5mO\x08\x0b\x81\xe4\x1e\n\x93^Kz\xd1=\xebA\xb3\xc0\x9b\x0e\x0c\xc1\xaf\x1b\x891\x90Mf\xf9\xad\xde\x0e\xabO\xb42\xa5\xd0e\n2\xa0\xf4\x1f\x94\x8e\xc4R\xd7\xd4\xef\xe7\x13\xb3\xe4\xa8tM\x03\xee_\xb3\xe04\xcb\x06\xe1K\x9b\x99*U\x16\x8f\x13:\xa2Cu\x95_\xa4(D\xdc\x83\x0f)IA\x8d\xf5\xfd\x00\xbd\xe8\xc2(\xd4\xcb\x17wc\x8e\x1cl\xe5\x80\xdc"\rJ\xf8\xb8\x17\x1e\x90\xef\xce\x93h\xb9\xa3E~\x11<R\xfe\xab\x88M\x12`\x05$\xd9*\x02\xced\xc0\x8a\xe4)Rs\x96\xe4z\xf5x\x9a\x99\xde\xa7\xd7\x94\x85\xef@\' e\xdc\x13\x8e\xa2T\xd6z\xad=\x0c\xcfs\n\x021\xe8a\xa3\xab<\xfa\xd3\x8d\x15}\x86\x99"=\xb3\'\x8e\xc3\xf3Z\xd5X\xfe\xb7J\xf7\xa3E5\x8b:\x9f\x12\xb1z:\xe7\xd0o \xb7"$mZ\xddz\xe5\x17\x07\xd5\xe8\x80\xec\x7fx\x08\xef>\xa5j\xe7\xa5\x85\xcf\xacs\xb2\xa4\x05#\xd1\x9d\xb1$\xa4\xce\x90B\xf4<\xc1\t\xf7\xf2\x85\xc5\xad\x93\xf3\xc4\x02z\x18\x1a\xe5~\x8c\x9eV+\xda\xb3\xec\xe2\xf7*\x9a\x11+\xef\xd5\x07\'_Pd\xfd\x8e\x99\x14\xd8\x08\xf8\xf8\xc9Zg\xd3\xe7\xf5 \xf5v\xe1[\xa0\xaf`\x1a\x84\xd70\x98\xb2P\xd3_qT\xe7\x18\xe5\xc5=L\nM^\x86SJ\x0e\xb5X\x9b\xfdtH\xcbo3\xb9\x80\xdb\xd7\x93\xab\xe52@\x15C\x927p\x7f\xc0\x83\xc1\xcc\xa0\xcbd\xc2\xd8\xa2|\x053\x1c\xbcQ\xd7\xc2\x84\x0e\xd4(\xf4Z\x82Z0k\xdaE\xba_-\xd8\x87\xdf\x8a%\xebT\xdd\x16\x1c\xdb\xe1\xfa\xe5\xfd\xaa\x0ePy\'\x08\xd9\xd0"\re\xd0\xcb\x7f8\xb8z@\x19\xc9\xf4Tf\xa1H \xc65|\xa3C\xcb4\x94)P\xfe\xadH\xa0f4\xda\x92(\x99\xeb\x9b\xd2\x88\xe6\xcbQ7\x10\x91\x02u\xaa\x1d5\xe9B\xcd\x8d\x93\xfdY\xce\xef\xedYy?E\x0e\x99\xa1P7\xc1\xbf\xaaQ\xbf\xff\xbb\xd5\x13m!\xbd\xb2\x8fr\xc3\xdc\x0c b\xc9\xafF\'d:\xc2I\xc1\xafV\xb4\xdb\x06z\xa4\xe6\xe1RQ\x14Y\x94\xd5\xe0\x14-d\x1eA\xed\x14p\xe6\x11\x84:e\x03P\xed\xa3\xf4\xd2\xf4\x86C\x8f\xd0\x1a"\xbe\xcc\xa4B\xe88\xcd\xa5\xce\x14\x1b1m\nO\xb1\x83\x02\xa1>\x12\x99\xcf^.n\xba\xee \xb5\x8d.?%\xef\xc1\xe7\xe5"TA\x99\x02\x87J\xc7\xf9\x0e;\\\x0f%"7\x0c\xf8Y\xf5\x07\xf9a\xa1\xa17J\n\x1a2c\xa1s\xae\xfd\x0e\xde\xe8\r\x9d\x89\xb7\xb2X\x9e\x86\xdd\x84\xc4[\xb5\xa3x\xb510\xb1\xef\x9f\xe5Z\xd8\x8d\xf2\x19\xf4O\xccp\xb1\xb5w\x99<>\xdf\xc6\x93\xef\xd6\x11\n\xa1L\xed\x95\x16\r\xc0<\xbeG\x9e\xb6\xe66\xdbu\x90\xe2\x8b:\xc2\x9d`&&\x04\\\x07\x7fM\xfb\xb4M\x89V2\xb7\xed\xa4\xf2\x9ey-X?d\x91\x9cI\xa3Z$\xaa\xf0\x9bw\x8d\xa7\x8a\xf4\xee\xa0T1\x063\x13\xfeJ\xea\x84\xe5\xf8\x97i<\xcc\xe0\x8d\x1f\x0f\x7f\x16\x82{\xef^\xc9E\x01\x81\xaa\xaf\xe7\xde\xa8H}\xa7\xe6\xbcnQ\x8aMv\x1a\xc2\xf6\x0c\x07\xf9\x8f\xc3\x07\xf6\x18\xe9\xdc>\xd0S\x81C&K\x05\xf3\xdf\x99\xb6\x9b"\x95\x1d\xee\x88b\xe37\x1a^0\xc4)\xb2\xf5\x8f9!3\x98{e\x93\xc8\\/6\xaf\xab\xef\xc0\x03\xb8\xe7"TW\xbd\xfa\xb0\x1d\x8bS\x16$l\x06\x99\xcdeDWyN\x82\xbe\r{\xe1\x87\xe1\xec\xb5v\x86\xd6\xaf8\xba\xcd\x1c-\xa7\xbd\xbcb\x17\x1c[\x86S\x10\xa7\xc5\x1e\xfc\xda\xef\x07\xe1\xbb\xd3$+\x91E\x8cx\xbep\xb7\xcdI\xb9\xbb\xdchH</\x0b\x0fD\x80\xc2{\xffW\xd6EM\xa2\x96\xa8\xa5d\x03\xbb4\x10q\x9d\xda\x0f,J\r\xab\xfc\xda\xcb\'y{\x91sp\xdb\xcb\x05*\xff\xd25X\xc8\x11\xbfl|\xc8\x11\x0f:\x91\xf8\xcd\xa2Q&[\xc8f\xaf\xb9/\xa2\xb6C\x91\x10\xf3~\xee\xb7\xfau,\xeaX\xe2\xff\x84#\xfclp\xab\xc5\xda\xcc\xbb\x11\xe1]\xb8\xde\x8f\xc3\x93\x95\x8f\x94yd\xb1n\x97\xb4r<\x106o\xb4\xea.e\xa5sk-\xac_Xh\x11\xbf\x0c\xde\xa5\x86\x07\xf5z\x83\x03\xf4\xd7\xe1\xbc\xa6\rG\xe7.\xae\x0e\xe43\xf1\x1c\xa2\xac \xddZ\x16>\xc4@\x04\xb8\xfc\x8e\xc8\x95\x177ZR\xf7\xa7S\x7f\xbfVSp\xbd\xfa\xc30_f>N\xecf\xda\xf0l;\x12\x13I\xf8\x9d\xeb\xda\x93\x14\xe5fc\x87F+\xd2,\xe3\x00\xb3\x93\xd1P@\xf5\xbf\x11\x1b\xb9;\xe1h\xd9<\xebL\xb4F\xa1\x80\'\xda\xaa\xc5\xf8\'\xf9r\xacu\xb1\xc5\x9eO\x8bS\x8dZv^s\x93iu\xf0\x18;Z\xf0*\xe1@Ax\xf2\x8b\xb1lMG\xeb\xd8\xcc\xb5\xa8\xd4X\\9xPk\xc4\x98N\xf1\x11\xf5j\xf6\x9d3\xbf"\x9f\xa9\xf3[,\xf6d\x05\x93\x95\x07\xe7\x0f\xfd\xadiF\xa5E\x0eKM\xf8X\xae\xda\x92\x89\x1c\x95:\r{K\x89\x85\x00K\x19\xf0\xccxH\x1e\x92\xd2\x02\x88%\xb3=\xc2\x92P_2\xa7C\xab\x9d\xee\x07M\x17~B\xc4\xe4\xaa6\xa9L\x83\xe1[]R\xba\xf0\xa0\xd6\xab\xf1\xd7\x14\x81\xa56\xa1\xa1\xd7\xf3\xfd\x94KQ,LXj\xd6\xc4\x92~R2\x9f\x81\x11\xfe\x85\xc4\x19I!\xb7\xa9\xe4\xb1\xb4\xf8\xa0\xfcT\xceUX\\\x1cxP\xae\xa9\x8c\xe4\xb1\xc9;:\xaf>\xf6\xc7\xd1\x9c\x0c\xa5\xc5\xffJ\xe68\xb80u\xc9\xc4\x85v\xd39\n,\x15\x9bW\xdb\xf1\x8e[\xc8\x9b\xcf\x0cn\xd1\xfd\x8f;\xd1\xe1\xd3\xb6\xd4\x99j\xbd\xee6\xad\xa7*\xbaZ\xf0kz\x82\xd5/\xfa.j\x14zV\x91M;\xc6I4c\xdb\x086\x89 \x0e\\\xe9\x17*\xb7U\x19\xfcBg\xa1\xb5\x9aFsL\x94\x16",5a\xa2\xf6+DH-l\xfcP\xb9\xd5t\x16\xb3H\xd4\xbc\x9a.S\xa8}\xb5\x10\x1e\x88rV\xfb\xd5\xdc\x0e\x07\x11\xeb"\x06o\xc5\xe4P\x9f\xbd|sQ\xf8G\xc4#L-BEZf^9^\xd5\x92<#\x0f\xc4\xdai\xc1\xbc\xfd\xfc\xa0\xe9\xc1\xb4\x90n&\xd4\x85\xcc\xe6\x00C\xcec\x9a^\x91\x198TrG\xf8\x05"s\xa1\xf3\x0b\xdc\x9eN\x0f\xba\xc0\x13\xc3QF!s1\xaa]\x83_`\x80\xf6y

**The Subtitles are zipped. So we need to unzip it first**

In [7]:
import zipfile
import io

# Unzipping the Subs
def extract_subtitle(binary_data):
    zip_file = zipfile.ZipFile(io.BytesIO(binary_data))
    subtitle = zip_file.read(zip_file.namelist()[0]).decode("latin-1")
    return subtitle

In [8]:
data["subtitle"] = data["content"].apply(extract_subtitle)

In [9]:
data['subtitle'][0]

'1\r\n00:00:06,000 --> 00:00:12,074\r\nWatch any video online with Open-SUBTITLES\r\nFree Browser extension: osdb.link/ext\r\n\r\n2\r\n00:02:26,198 --> 00:02:29,953\r\nIn the name of God, the most gracious, the most Merciful.\r\n\r\n3\r\n00:02:31,072 --> 00:02:33,370\r\nFrom Muhammad, the Messenger of God\r\n\r\n4\r\n00:02:33,550 --> 00:02:36,047\r\nto Heraclius, the emperor of Byzantium.\r\n\r\n5\r\n00:02:36,407 --> 00:02:39,464\r\ngreetings to him who is the\r\nfollower of righteous guidance.\r\n\r\n6\r\n00:02:39,783 --> 00:02:42,591\r\nI bid you to hear the divine call.\r\n\r\n7\r\n00:02:43,160 --> 00:02:45,817\r\nI am the messenger of God to the people;\r\n\r\n8\r\n00:02:46,337 --> 00:02:48,784\r\naccept Islam for your salvation.\r\n\r\n9\r\n00:02:52,231 --> 00:02:54,709\r\nHe speaks of a new prophet in Arabia.\r\n\r\n10\r\n00:02:55,068 --> 00:02:57,825\r\nWas it like this when John, the Baptist\r\ncame to king Herod\r\n\r\n11\r\n00:02:58,145 --> 00:03:01,272\r\nout of the desert, crying about salvation?\r\n\r\n12\r\n00:03:26,136 --> 00:03:28,903\r\nTo Muqawqis, Patriarch of Alexandria.\r\n\r\n13\r\n00:03:42,400 --> 00:03:44,638\r\nKisra, emperor of Persia.\r\n\r\n14\r\n00:03:44,757 --> 00:03:47,495\r\nMuhammad calls you with the call of God.\r\n\r\n15\r\n00:03:47,714 --> 00:03:50,551\r\nAccept Islam for your salvation...\r\n\r\n16\r\n00:03:50,890 --> 00:03:52,449\r\nembrace Islam.\r\n\r\n17\r\n00:03:54,267 --> 00:03:58,722\r\nYou come out of the desert,\r\nsmelling of camel and goat.\r\n\r\n18\r\n00:03:58,782 --> 00:04:00,810\r\nTo tell Persia where he should kneel?\r\n\r\n19\r\n00:04:09,332 --> 00:04:11,600\r\nMuhammad, Messenger of God.\r\n\r\n20\r\n00:04:13,648 --> 00:04:15,306\r\nWho gave him this authority?\r\n\r\n21\r\n00:04:15,785 --> 00:04:18,742\r\nGod sent Muhammad\r\nas a mercy to mankind.\r\n\r\n22\r\n00:05:13,357 --> 00:05:25,274\r\nThe Scholars and Historians of Islam -\r\nThe University of Al-Azhar in Cairo\r\nThe High Islamic Congress of the Shiat in Lebanon\r\n\r\n23\r\n00:05:26,103 --> 00:05:33,745\r\nThe makers of this film honour the Islamic tradition\r\nwhich holds that the Impersonation of the Prophet\r\noffends against the spirituality of his message.\r\n\r\n24\r\n00:05:33,785 --> 00:05:45,384\r\nTherefore, the person of Mohammad\r\nwill not be shown.\r\n\r\n25\r\n00:05:50,009 --> 00:05:53,046\r\n<i>600 years after Christ died,</i>\r\n\r\n26\r\n00:05:53,246 --> 00:05:55,742\r\n<i>when Europe was sunk in the dark ages</i>\r\n\r\n27\r\n00:05:55,802 --> 00:05:58,679\r\n<i>and everywhere the old\r\ncivilizations were falling,</i>\r\n\r\n28\r\n00:05:58,779 --> 00:06:02,356\r\n<i>Muhammad was born\r\nin Mecca, in Arabia.</i>\r\n\r\n29\r\n00:06:02,975 --> 00:06:07,151\r\n<i>Mecca was then a rich trading\r\ncity, ruled by its merchants</i>\r\n\r\n30\r\n00:06:07,351 --> 00:06:10,687\r\n<i>whose wealth was multiplied\r\nby a unique privilege...</i>\r\n\r\n31\r\n00:06:10,907 --> 00:06:12,645\r\n<i>they housed the gods.</i>\r\n\r\n32\r\n00:06:13,125 --> 00:06:16,002\r\n<i>Every year, at the\r\ntime of the great fair,</i>\r\n\r\n33\r\n00:06:16,242 --> 00:06:18,490\r\n<i>the desert priests brought their idols</i>\r\n\r\n34\r\n00:06:18,500 --> 00:06:21,686\r\n<i>and the images of their gods\r\ninto the custody of the Kaaba.</i>\r\n\r\n35\r\n00:06:53,663 --> 00:06:56,650\r\n<i>Once, the most holy shrine of Abraham,</i>\r\n\r\n36\r\n00:06:56,860 --> 00:06:59,607\r\n<i>the Kaaba had now\r\nbecome a house of idolotry</i>\r\n\r\n37\r\n00:06:59,857 --> 00:07:04,383\r\n<i>hosting no fewer than\r\n360 different gods.</i>\r\n\r\n38\r\n00:07:05,721 --> 00:07:09,477\r\n<i>Mecca in 610 A.D.</i>\r\n\r\n39\r\n00:07:40,895 --> 00:07:41,754\r\nBilal!\r\n\r\n40\r\n00:07:50,885 --> 00:07:52,523\r\nHave you had today\'s count Umaya?\r\n\r\n41\r\n00:07:52,623 --> 00:07:53,383\r\nNot yet...\r\n\r\n42\r\n00:07:53,922 --> 00:07:56,160\r\nbut this year the Gods are gold.\r\n\r\n43\r\n00:07:56,360 --> 00:08:00,366\r\nWhen you put the Gods and Prophet together,\r\nyou sit very pretty between hmm?\r\n\r\n44\r\n00:08:00,964 --> 00:08:03,891\r\nAnd more gods to place in the Kaaba.\r\n\r\n45\r\n00:08:09,176 --> 00:08:10,395\r\nCaravan from Syria.\r\n\r\n46\r\n00:08:12,023 --> 00:08:16,788\r\n- Hmm...they must have been running.\r\n- They\'ll be thirsty.\r\n\r\n47\r\n00:08:16,798 --> 00:08:18,616\r\nPut five more men on north wells.\r\n\r\n48\r\n00:08:19,196 --> 00:08:21,423\r\nHow many sheep shall\r\nI have to kill for them?\r\n\r\n49\r\n00:08:21,683 --> 00:08:22,393\r\n70?\r\n\r\n50\r\n00:08:22,402 --> 00:08:23,451\r\nGive them a hundred.\r\n\r\n51\r\n00:08:23,571 --> 00:08:25,939\r\nMecca must keep her\r\nname for hospitality.\r\n\r\n52\r\n00:08:28,037 --> 00:08:29,765\r\nAnd ten lambs for the leaders.\r\n\r\n53\r\n00:08:38,776 --> 00:08:42,591\r\nBread and water,\r\ndo the poets have in the Hakim\'s house?\r\n\r\n54\r\n00:08:43,031 --> 00:08:47,446\r\nWhere verse and prose are\r\nnightly put to slaughter.\r\n\r\n55\r\n00:08:50,463 --> 00:08:53,690\r\nAnd...and the bread, I swear in there,\r\n\r\n56\r\n00:08:53,700 --> 00:08:55,808\r\nis thinner than the water!\r\n\r\n57\r\n00:08:57,706 --> 00:09:01,153\r\nOh...open the space, open the space,\r\nyou lovers of poetry,\r\n\r\n58\r\n00:09:01,253 --> 00:09:05,139\r\nto Abu Sufian, willing and which...\r\n\r\n59\r\n00:09:05,948 --> 00:09:07,766\r\npatron of the arts.\r\n\r\n60\r\n00:09:08,695 --> 00:09:12,142\r\nWhen Abu Sofyan invites the poet in,\r\n\r\n61\r\n00:09:12,272 --> 00:09:16,058\r\ntheir joy is kit and love is kin.\r\n\r\n62\r\n00:09:16,537 --> 00:09:18,345\r\nWhere wines and cakes abound,\r\n\r\n63\r\n00:09:18,435 --> 00:09:20,124\r\nthe skills of Abu Sofyan.\r\n\r\n64\r\n00:09:21,213 --> 00:09:23,980\r\nAll revels and all songs begin,\r\n\r\n65\r\n00:09:24,090 --> 00:09:28,105\r\nwhen Abu Sofyan invites the poet in.\r\n\r\n66\r\n00:09:43,070 --> 00:09:45,907\r\nFrom the silkworms of China, my lady.\r\n\r\n67\r\n00:09:46,586 --> 00:09:48,354\r\nA pleasure to the limb...\r\n\r\n68\r\n00:09:48,884 --> 00:09:53,339\r\nand as my lady can see,\r\na ravish to the eye.\r\n\r\n69\r\n00:09:57,445 --> 00:09:59,513\r\nYes, 7 lengths.\r\n\r\n70\r\n00:09:59,543 --> 00:10:00,612\r\n20 dinars.\r\n\r\n71\r\n00:10:00,912 --> 00:10:02,430\r\nAbu Sofyan\'s wife?\r\n\r\n72\r\n00:10:04,488 --> 00:10:05,437\r\n15.\r\n\r\n73\r\n00:10:28,034 --> 00:10:32,759\r\nOh, gold! The gods of the\r\nKaaba have their needs,\r\n\r\n74\r\n00:10:32,779 --> 00:10:34,267\r\ntheir upkeeps.\r\n\r\n75\r\n00:10:43,848 --> 00:10:48,193\r\nWho is that man who stood there,\r\nwho looked into my soul?\r\n\r\n76\r\n00:10:50,660 --> 00:10:52,428\r\nCarry me away from here.\r\n\r\n77\r\n00:10:58,312 --> 00:11:00,231\r\nWhy must Muhammad come down here?\r\n\r\n78\r\n00:11:00,510 --> 00:11:01,959\r\nWhy don\'t you stop him?\r\n\r\n79\r\n00:11:02,069 --> 00:11:03,098\r\nHe is your nephew.\r\n\r\n80\r\n00:11:03,787 --> 00:11:04,986\r\nMaybe he will change.\r\n\r\n81\r\n00:11:05,046 --> 00:11:06,115\r\nChange?\r\n\r\n82\r\n00:11:06,424 --> 00:11:08,432\r\nHe is 40 years old.\r\n\r\n83\r\n00:11:09,801 --> 00:11:11,100\r\nIt\'s unnatural...\r\n\r\n84\r\n00:11:11,419 --> 00:11:14,936\r\nwith a rich wife, he could\r\nafford the best of Mecca.\r\n\r\n85\r\n00:11:15,096 --> 00:11:17,613\r\nYet he chooses to sit shivering in a cave.\r\n\r\n86\r\n00:11:18,023 --> 00:11:19,601\r\nIt is unnatural!\r\n\r\n87\r\n00:11:19,761 --> 00:11:23,687\r\nFor a man who dares to\r\nrisk the anger of Al-Uzza,\r\n\r\n88\r\n00:11:23,937 --> 00:11:25,186\r\nwho keeps our health.\r\n\r\n89\r\n00:11:25,725 --> 00:11:28,742\r\nManat, the god of our prosperity.\r\n\r\n90\r\n00:11:29,660 --> 00:11:33,256\r\nAllat, the god of our\r\nfamily and tribes.\r\n\r\n91\r\n00:11:33,986 --> 00:11:35,314\r\nand Hubal...\r\n\r\n92\r\n00:11:35,534 --> 00:11:40,010\r\nHubal, who starts our caravans\r\nand predicts our fate.\r\n\r\n93\r\n00:11:40,279 --> 00:11:44,166\r\nTo challenge the gods within earshot\r\nof the gods is dangerous.\r\n\r\n94\r\n00:11:44,285 --> 00:11:45,145\r\nUnreasonable.\r\n\r\n95\r\n00:11:45,155 --> 00:11:47,642\r\nRebellious, blasphemous.\r\n\r\n96\r\n00:11:48,112 --> 00:11:52,207\r\nYes, I\'m afraid Muhammad\r\nwill harm himself.\r\n\r\n97\r\n00:12:05,784 --> 00:12:08,741\r\nI am always sad\r\nwhen the great fair is over.\r\n\r\n98\r\n00:12:10,479 --> 00:12:12,157\r\nI might not see the next one.\r\n\r\n99\r\n00:12:17,181 --> 00:12:19,759\r\nAbu Talib! Abu Talib!\r\n\r\n100\r\n00:12:21,627 --> 00:12:23,355\r\nCatch your breath, Zaid!\r\n\r\n101\r\n00:12:23,845 --> 00:12:25,603\r\nHas Muhammad come down\r\nfrom Mount Hira yet?\r\n\r\n102\r\n00:12:26,212 --> 00:12:27,461\r\nHe\'s been up there three days.\r\n\r\n103\r\n00:12:28,900 --> 00:12:32,137\r\nNo, no, I haven\'t seen him.\r\n\r\n104\r\n00:12:33,165 --> 00:12:35,513\r\nKhadijah hoped he might have\r\ncome to you on his way home.\r\n\r\n105\r\n00:12:37,191 --> 00:12:38,430\r\nThen he\'s still up there.\r\n\r\n106\r\n00:12:40,148 --> 00:12:41,068\r\nThree days.\r\n\r\n107\r\n00:12:45,743 --> 00:12:47,601\r\nI\'m afraid for him on the mountain,\r\n\r\n108\r\n00:12:48,520 --> 00:12:49,359\r\nbecause...\r\n\r\n109\r\n00:12:50,488 --> 00:12:52,097\r\nI don\'t know what it means.\r\n\r\n110\r\n00:12:54,713 --> 00:12:58,219\r\n<i>Men see the world too well\r\nfrom a mountain.</i>\r\n\r\n111\r\n00:13:31,936 --> 00:13:35,032\r\nMuhammad! Read!\r\n\r\n112\r\n00:13:36,630 --> 00:13:40,926\r\nIn the name of thy Lord who created\r\nman from His sensitive drop of blood.\r\n\r\n113\r\n00:13:42,264 --> 00:13:44,722\r\nWho teaches man what he knows not.\r\n\r\n114\r\n00:13:46,001 --> 00:13:46,930\r\nRead!\r\n\r\n115\r\n00:14:26,919 --> 00:14:28,927\r\nHe\'s still trembling under the blanket...\r\n\r\n116\r\n00:14:30,815 --> 00:14:32,053\r\nbut he has spoken.\r\n\r\n117\r\n00:14:32,813 --> 00:14:36,329\r\nZaid! What happened to\r\nmy nephew on the mountain?\r\n\r\n118\r\n00:14:39,886 --> 00:14:41,724\r\nHe was alone, in the cave.\r\n\r\n119\r\n00:14:45,840 --> 00:14:48,557\r\nSuddenly, an angel came in to him.\r\n\r\n120\r\n00:14:50,645 --> 00:14:53,402\r\nThe angel said: Read!\r\n\r\n121\r\n00:14:55,990 --> 00:14:59,175\r\nMuhammad replied: I can not read.\r\n\r\n122\r\n00:15:01,003 --> 00:15:04,300\r\nThe angel commanded again: Read!\r\n\r\n123\r\n00:15:05,199 --> 00:15:06,428\r\nIn the name of thy Lord,\r\n\r\n124\r\n00:15:07,317 --> 00:15:10,014\r\nwho created man from\r\nHis sensitive drop of blood,\r\n\r\n125\r\n00:15:11,133 --> 00:15:13,301\r\nwho teaches man what he knows not.\r\n\r\n126\r\n00:15:14,330 --> 00:15:15,229\r\nRead!\r\n\r\n127\r\n00:15:18,416 --> 00:15:20,634\r\nWho knows if it was Gabriel?\r\n\r\n128\r\n00:15:23,001 --> 00:15:24,470\r\nIt could have been a dream.\r\n\r\n129\r\n00:15:26,788 --> 00:15:31,053\r\nWhen Muhammad was coming from\r\nthe mountain, he saw Gabriel plainly.\r\n\r\n130\r\n00:15:31,493 --> 00:15:33,611\r\nIn the shape of a man\r\nstanding on the horizon.\r\n\r\n131\r\n00:15:34,810 --> 00:15:35,729\r\nWherever he looked,\r\n\r\n132\r\n00:15:36,468 --> 00:15:38,846\r\nupon every turn of\r\nhis head he saw him.\r\n\r\n133\r\n00:15:40,962 --> 00:15:42,671\r\nAnd Gabriel said to him again,\r\n\r\n134\r\n00:15:44,209 --> 00:15:46,927\r\nI am Gabriel...\r\n\r\n135\r\n00:15:49,104 --> 00:15:50,593\r\nand you Muhammad,\r\n\r\n136\r\n00:15:52,231 --> 00:15:53,850\r\nare the Messenger of God.\r\n\r\n137\r\n00:15:59,694 --> 00:16:01,262\r\nWho has he told about this?\r\n\r\n138\r\n00:16:02,681 --> 00:16:03,430\r\nHis wife,\r\n\r\n139\r\n00:16:04,319 --> 00:16:05,138\r\nand Ali,\r\n\r\n140\r\n00:16:07,076 --> 00:16:09,754\r\nand, his friend Abu Bakr.\r\n\r\n141\r\n00:16:10,513 --> 00:16:11,382\r\nAnd you?\r\n\r\n142\r\n00:16:12,291 --> 00:16:14,029\r\nI am his adopted son.\r\n\r\n143\r\n00:16:16,527 --> 00:16:18,215\r\nBe careful to whom you talk.\r\n\r\n144\r\n00:16:22,140 --> 00:16:26,965\r\nTell him his uncle who protected him\r\nwhen he was a child, will protect him still.\r\n\r\n145\r\n00:16:27,755 --> 00:16:28,594\r\nAfter all...\r\n\r\n146\r\n00:16:31,351 --> 00:16:33,009\r\nthey say the God of Moses\r\n\r\n147\r\n00:16:33,019 --> 00:16:35,237\r\nspoke to him out of a burning bush.\r\n\r\n148\r\n00:16:42,040 --> 00:16:44,478\r\nIf you do not restrain\r\nyour nephew then we will.\r\n\r\n149\r\n00:16:44,838 --> 00:16:47,275\r\nHe\'s dividing the city,\r\nheart against house.\r\n\r\n150\r\n00:16:47,695 --> 00:16:50,172\r\nHe\'s dividing the generations\r\nchild against parent.\r\n\r\n151\r\n00:16:51,051 --> 00:16:52,720\r\nThe young are listening to him.\r\n\r\n152\r\n00:16:53,888 --> 00:16:55,217\r\nHe attracts the young.\r\n\r\n153\r\n00:16:57,465 --> 00:17:01,011\r\nWe are Arabs,\r\nwe obey our fathers.\r\n\r\n154\r\n00:17:01,061 --> 00:17:03,099\r\nOur children cannot be our teachers.\r\n\r\n155\r\n00:17:04,037 --> 00:17:07,614\r\nHow can we accept that the man\r\nwe met in the street yesterday\r\n\r\n156\r\n00:17:07,754 --> 00:17:10,920\r\ncan be some God\'s Prophet today?\r\n\r\n157\r\n00:17:11,400 --> 00:17:14,267\r\nDead bones can live again, he says\r\n\r\n158\r\n00:17:14,447 --> 00:17:16,215\r\nbecause He who created man\r\n\r\n159\r\n00:17:16,225 --> 00:17:19,762\r\ncan also make man return\r\nfrom the dead, he says!\r\n\r\n160\r\n00:17:20,930 --> 00:17:24,157\r\nThe Gods might leave us and\r\ngive their benefits to another city.\r\n\r\n161\r\n00:17:27,644 --> 00:17:32,419\r\nTell him...we will give him\r\nauthority, position,\r\n\r\n162\r\n00:17:34,047 --> 00:17:35,336\r\nand keys to the Kaaba,\r\n\r\n163\r\n00:17:36,225 --> 00:17:38,383\r\nand money, what money he wants.\r\n\r\n164\r\n00:17:41,969 --> 00:17:44,547\r\nTell him, we will give\r\nhim anything he wants.\r\n\r\n165\r\n00:18:08,951 --> 00:18:14,106\r\nMuhammad, spare yourself\r\n...and me.\r\n\r\n166\r\n00:18:15,525 --> 00:18:18,632\r\nDo not put a greater burden on\r\nan old man that he can bear.\r\n\r\n167\r\n00:18:21,319 --> 00:18:23,697\r\nIn your childhood, you were in my arms.\r\n\r\n168\r\n00:18:24,965 --> 00:18:26,833\r\nI cannot now see you hurt.\r\n\r\n169\r\n00:18:28,990 --> 00:18:30,429\r\nIf you refuse them...\r\n\r\n170\r\n00:18:31,768 --> 00:18:32,946\r\nthey will hurt you.\r\n\r\n171\r\n00:18:48,191 --> 00:18:49,370\r\nHe said this to me:\r\n\r\n172\r\n00:18:50,888 --> 00:18:54,245\r\nWere they to put the sun in my\r\nright hand and the moon in my left,\r\n\r\n173\r\n00:18:55,674 --> 00:18:57,742\r\nI would not renounce my message,\r\n\r\n174\r\n00:18:58,641 --> 00:18:59,740\r\nwhich is from God.\r\n\r\n175\r\n00:19:05,604 --> 00:19:07,462\r\nWhen I am dead,\r\nyou may do as you please,\r\n\r\n176\r\n00:19:07,811 --> 00:19:09,838\r\nbut whilst I\'m alive,\r\nyou will obey your father!\r\n\r\n177\r\n00:19:09,848 --> 00:19:11,287\r\nWhy did you hurt our father?\r\n\r\n178\r\n00:19:12,985 --> 00:19:17,001\r\nIf I were drunk every day\r\nand played dice every night,\r\n\r\n179\r\n00:19:17,740 --> 00:19:19,509\r\nyou\'d call it high spirits!\r\n\r\n180\r\n00:19:19,519 --> 00:19:21,457\r\nYou will be more my\r\nbrother than you are now!\r\n\r\n181\r\n00:19:21,697 --> 00:19:23,744\r\nYou are all my children.\r\n\r\n182\r\n00:19:31,407 --> 00:19:32,885\r\nI\'ve given you everything I could,\r\n\r\n183\r\n00:19:34,264 --> 00:19:36,272\r\nbut it seems not to be enough.\r\n\r\n184\r\n00:19:38,100 --> 00:19:39,898\r\nMuhammad gives me more,\r\n\r\n185\r\n00:19:40,757 --> 00:19:42,815\r\nhe give all the world more.\r\n\r\n186\r\n00:19:42,935 --> 00:19:44,494\r\nGet him out of here, father!\r\n\r\n187\r\n00:19:57,240 --> 00:19:59,757\r\nIt\'s not Waleed or me,\r\nit\'s our father.\r\n\r\n188\r\n00:20:00,517 --> 00:20:01,705\r\nYou tortured him.\r\n\r\n189\r\n00:20:10,467 --> 00:20:12,355\r\nWait Hudayfa, wait!\r\n\r\n190\r\n00:20:17,660 --> 00:20:19,997\r\nHow can they say\r\nit\'s an invention, Musab,\r\n\r\n191\r\n00:20:20,277 --> 00:20:21,356\r\nwhen it isn\'t new?\r\n\r\n192\r\n00:20:21,875 --> 00:20:23,773\r\nIn Mecca, it\'s new.\r\n\r\n193\r\n00:20:24,133 --> 00:20:26,081\r\nYet, God has said it all before...\r\n\r\n194\r\n00:20:27,180 --> 00:20:30,507\r\nto Noah, Moses, Jesus\r\nto all the Prophets,\r\n\r\n195\r\n00:20:30,866 --> 00:20:34,502\r\nbut people changed it,\r\nturned it, forgot it.\r\n\r\n196\r\n00:20:36,679 --> 00:20:38,478\r\nNow God said it to Muhammad again...\r\n\r\n197\r\n00:20:39,557 --> 00:20:40,915\r\nand it is new again.\r\n\r\n198\r\n00:20:45,331 --> 00:20:46,010\r\nWhat is it?\r\n\r\n199\r\n00:20:46,590 --> 00:20:47,349\r\nIt\'s Jafar.\r\n\r\n200\r\n00:21:02,074 --> 00:21:03,353\r\nWhat have you brought with you?\r\n\r\n201\r\n00:21:04,442 --> 00:21:05,810\r\nThe very word of God.\r\n\r\n202\r\n00:21:15,270 --> 00:21:16,838\r\nWhen the sun is overthrown.\r\n\r\n203\r\n00:21:17,687 --> 00:21:19,256\r\nWhen the stars fall.\r\n\r\n204\r\n00:21:20,455 --> 00:21:22,173\r\nWhen the mountains vanish.\r\n\r\n205\r\n00:21:23,112 --> 00:21:25,809\r\nWhen the camels big with\r\nyoung are abandoned.\r\n\r\n206\r\n00:21:26,908 --> 00:21:29,346\r\nWhen the wild beasts are herded together.\r\n\r\n207\r\n00:21:30,525 --> 00:21:32,243\r\nWhen the seas rise.\r\n\r\n208\r\n00:21:33,262 --> 00:21:35,040\r\nWhen the souls are sorted.\r\n\r\n209\r\n00:21:36,009 --> 00:21:38,666\r\nWhen the female infant\r\nwho is buried alive,\r\n\r\n210\r\n00:21:39,396 --> 00:21:41,853\r\nasks for what crime she was killed.\r\n\r\n211\r\n00:21:43,512 --> 00:21:45,190\r\nWhen the books are opened.\r\n\r\n212\r\n00:21:46,349 --> 00:21:48,646\r\nWhen the sky is torn away,\r\n\r\n213\r\n00:21:49,426 --> 00:21:50,385\r\nthen...\r\n\r\n214\r\n00:21:51,384 --> 00:21:52,902\r\nevery soul...\r\n\r\n215\r\n00:21:53,462 --> 00:21:55,020\r\nwill know what it has done.\r\n\r\n216\r\n00:21:58,256 --> 00:22:02,961\r\nWere you there, Jafar\r\nwhen God gave him these words?\r\n\r\n217\r\n00:22:17,676 --> 00:22:18,765\r\nDawn is coming up.\r\n\r\n218\r\n00:22:28,086 --> 00:22:29,884\r\nAmmar, you first,\r\n\r\n219\r\n00:22:31,413 --> 00:22:32,462\r\nthen you Jaafar.\r\n\r\n220\r\n00:23:30,222 --> 00:23:30,961\r\nAmmar!\r\n\r\n221\r\n00:23:34,607 --> 00:23:36,875\r\nYou kept your mother awake\r\nall night with worry.\r\n\r\n222\r\n00:23:36,975 --> 00:23:37,944\r\nI\'m sorry father.\r\n\r\n223\r\n00:23:37,974 --> 00:23:38,913\r\nWhere were you?\r\n\r\n224\r\n00:23:39,592 --> 00:23:41,051\r\nHave you been with Muhammad again?\r\n\r\n225\r\n00:23:45,676 --> 00:23:46,995\r\nWhat will happen now?\r\n\r\n226\r\n00:23:51,490 --> 00:23:53,998\r\nForgive him, it was\r\nmy fault, I did it.\r\n\r\n227\r\n00:23:54,158 --> 00:23:56,555\r\nThat God has helped us all our lives.\r\n\r\n228\r\n00:23:56,775 --> 00:23:57,664\r\nBut it fell...\r\n\r\n229\r\n00:23:59,413 --> 00:24:01,151\r\nit could not even help itself.\r\n\r\n230\r\n00:24:01,650 --> 00:24:03,647\r\nWhat talk have you been listening to?\r\n\r\n231\r\n00:24:05,925 --> 00:24:07,743\r\nThe real god is unseen.\r\n\r\n232\r\n00:24:09,042 --> 00:24:10,490\r\nHe\'s not made of clay.\r\n\r\n233\r\n00:24:13,248 --> 00:24:17,873\r\nAmmar, we see the gods\r\nin the Kaaba every day.\r\n\r\n234\r\n00:24:19,262 --> 00:24:20,391\r\nI\'m afraid for you.\r\n\r\n235\r\n00:24:22,349 --> 00:24:25,865\r\nYou\'re listening to people\r\nwho will hurt you.\r\n\r\n236\r\n00:24:27,084 --> 00:24:29,042\r\nI\'m listening to Muhammad, mother.\r\n\r\n237\r\n00:24:29,611 --> 00:24:31,699\r\nMuhammad is generous, yes.\r\n\r\n238\r\n00:24:31,779 --> 00:24:33,417\r\nHe gives, he shares,\r\n\r\n239\r\n00:24:33,877 --> 00:24:35,835\r\nhe\'ll pass no man without a smile,\r\n\r\n240\r\n00:24:36,684 --> 00:24:39,471\r\nbut he is spreading dangerous ideas.\r\n\r\n241\r\n00:24:40,391 --> 00:24:43,078\r\nDangerous ideas,\r\nthat no man should start?\r\n\r\n242\r\n00:24:45,165 --> 00:24:47,103\r\nThat the rich should not afloat the poor?\r\n\r\n243\r\n00:24:48,621 --> 00:24:50,140\r\nThe strong should not oppress the weak?\r\

In [10]:
data

,num,name,content,subtitle
0,9180533,the.message.(1976).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x1c\xa9\x...,"1\r\n00:00:06,000 --> 00:00:12,074\r\nWatch an..."
1,9180583,here.comes.the.grump.s01.e09.joltin.jack.in.bo...,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x17\xb9\x...,"1\r\n00:00:29,359 --> 00:00:32,048\r\nAh! Ther..."
2,9180592,yumis.cells.s02.e13.episode.2.13.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00L\xb9\x99V...,"1\r\n00:00:53,200 --> 00:00:56,030\r\n<i>Yumi'..."
3,9180594,yumis.cells.s02.e14.episode.2.14.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00U\xa9\x99V...,"1\r\n00:00:06,000 --> 00:00:12,074\r\nWatch an..."
4,9180600,broker.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x001\xa9\x99V...,"ï»¿1\r\n00:00:06,000 --> 00:00:12,074\r\nWatch..."
...,...,...,...,...
82493,9521935,the.prophets.game.(2000).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\xb8\xa6\x...,"ï»¿1\r\n00:01:16,284 --> 00:01:19,537\r\nGod,\..."
82494,9521937,west.beirut.(1998).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x13\x97\x...,"1\r\n00:00:06,000 --> 00:00:12,074\r\napi.Open..."
82495,9521938,frankenstein.the.true.story.(1973).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00$\x97\x9aV...,"1\r\n00:00:01,001 --> 00:00:04,630\r\n(Dramati..."
82496,9521940,frankenstein.the.true.story.(1973).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x00\x97\x...,"1\r\n00:00:06,000 --> 00:00:12,074\r\nAdvertis..."
82497,9521941,zombie.island.massacre.(1984).eng.1cd,"b'PK\x03\x04\x14\x00\x00\x00\x08\x00,\x97\x9aV...","1\r\n00:00:01,919 --> 00:00:03,253\r\n(Sharp w..."

In [34]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 82498 entries, 0 to 82497
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   num       82498 non-null  int64
 1   name      82498 non-null  str
 2   content   82498 non-null  object
 3   subtitle  82498 non-null  str
dtypes: int64(1), object(1), str(2)
memory usage: 2.5+ MB

### Cleaning the subtitles

In [11]:
import re

def clean_subtitle(text):

    text = str(text)

    # Remove timestamps
    text = re.sub(r'\d{2}:\d{2}:\d{2},\d{3} --> \d{2}:\d{2}:\d{2},\d{3}', ' ', text)

    # Remove subtitle index numbers
    text = re.sub(r'\n?\d+\n', ' ', text)

    # Remove HTML tags like <i>, </i>
    text = re.sub(r'<.*?>', ' ', text)

    # Remove "Synced by ..." lines
    text = re.sub(r'synced\s*by\s*\w+', ' ', text, flags=re.I)

    # Remove OpenSubtitles ads
    text = re.sub(r'watch any video online with open[- ]?subtitles', ' ', text, flags=re.I)
    text = re.sub(r'free browser extension', ' ', text, flags=re.I)
    text = re.sub(r'please rate this subtitle.*', ' ', text, flags=re.I)
    text = re.sub(r'advertise your product or brand here.*', ' ', text, flags=re.I)
    text = re.sub(r'contact\s*www\.opensubtitles\.org.*', ' ', text, flags=re.I)
    text = re.sub(r'opensubtitles', ' ', text, flags=re.I)
    text = re.sub(r'osdb\.link\S*', ' ', text)

    # Remove URLs
    text = re.sub(r'http\S+|www\S+', ' ', text)

    # Remove weird encoding characters
    text = re.sub(r'[^\x00-\x7F]+', ' ', text)

    # Remove special characters
    text = re.sub(r"[^a-zA-Z\s']", ' ', text)

    # Fix contractions
    text = re.sub(r"\s+'\s+", "'", text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text)

    return text.lower().strip()

In [12]:
data["clean_text"] = data["subtitle"].apply(clean_subtitle)

In [13]:
data["clean_text"][3]

"yumi's cells episode laptop first place is mine mine oh yeah first place first place the unique sweetness is gone it's no fun writer kim yumi are you going through a hard time this is like a funeral march dragging on why did you make a sequel just end it if you don't have anything to say i can't read this anymore i'm leaving now what oh yeah first place the unique sweetness has disappeared everything is malicious comments it's because it's so popular there are no malicious comments if it's not popular but still there are too many malicious comments these days it's because the ending is almost near they must be worried that it won't be a happy ending don't worry too much about it writer you're going to give them a good ending a good ending our company's employees are all looking forward to it too since you're not giving them any hints they're all in suspense wondering what the ending will be what will the ending be i'm curious about that too won't you let me know what the ending will be cooking cell told me to bring this to you so you can gain some strength bye the ending is coming god yumi let's have a legendary ending although you get the full support of everyone once you become the top priority it's not necessarily a good thing oh no what should she do she has to end it well what should she do if it doesn't go well what if yumi can't give a good ending stop it they said they're looking forward to a good ending if it's not a good ending won't yumi be ostracized i said stop it please this cell is always clinging on to the prime cell anxiety if this doesn't go well it's all over we used all the down payment to buy the house we got a huge loan if things go badly how will we pay back the loan what to do what will we do what will we do i said stop it i'm so anxious that i can't write you'll send me the manuscript tomorrow morning before the wedding right ah i should miss writer fighting i'll see you at the ceremonial hall yes fighting yumi was already pretty stressed because she had to finish the manuscript for the sequel but the real incident occured the night before yi da's wedding reason emergency emergency what is it i don't see the laptop look for it it must be somewhere it's not there it's not in the place where she usually charges it no it's not then what about the table what about under the bed it's not there maybe she put it in another bag before she left no did it get mixed in with the recyclables i'm telling you it didn't it's not here it's gone how much of the manuscript is in the laptop including the episode that i'm going to upload tomorrow it's chapters in episodes that much you didn't make a backup she definitely left it somewhere outside before she came home what places did she visit today it's because the ending is almost near they must be worried that it won't be a happy ending there she had the laptop up until then yes miss writer your laptop yes we were looking at my laptop together this morning and talking about the comments that was my laptop though you didn't take your laptop out did you lose it how yes well i should look for it i'll find it you backed it up right as long as the manuscript is alright oh of course yes she must have really lost it let's not despair for now she can just go buy a new laptop tomorrow and rewrite it all rewrite it all pages don't you have the outline in your head in the end yumi couldn't find the laptop up to the morning of the wedding what will she do now everyone from the publishing company is going to the wedding what will she do what to do come up with an excuse there's no manuscript to upload today and there's no manuscript to upload next week either even if she writes there are malicious comments what do we do they won't leave i'm not being the prime cell anymore bye guys don't look for me ever again goodbye writer oh no writer abandoned her prime cell position and ran away thank you thank you thank you aigo writer yumi you made it editor in chief congratulations thank you where's yi da she's in the waiting room right now you finished by the deadline before you came right yes i'll read it after the ceremony i'm looking forward to the last chapter yes oh yes excuse me congratulations oh thank you the groom's side kim yumi wow miss yumi oh bon hui hello it's been a long time it's been so long i know it's good to see you wait i heard that you're the one who set up the bride and groom they said that the groom is your editor in chief i didn't set them up really he was a loser this time too yeah he was the worst of the worst it's not like i'm betting on who's worse hey i really got angry and miss writer oh editor in chief i saw you on my way to the publishing company oh i had plans with my friend so i was just about to get up and leave anyway yi da say hello this is my editor in chief i talked about him a lot right this is my former co worker yi da hello i'm kang yi da hello i'm ahn dae yong you're the best pardon you're the person that chose our yumi's work i always told yumi that you've got a great eye you've really got an amazing eye for writers that's because miss writer's writing is you're the best really the best what is this who is that cute creature she said she's kang yi da let's save that kang yi da kang yi da her name is kang yi da cute best jjang yi da the line is perfect too hello hello hello i'm ahn dae yong who greeted you last time you remember me right oh this ahjusshi yes of course hello how have you been i have a meeting nearby today if it's okay with you shall we have lunch together julie literature editor in chief ahn dae yong yes that sounds good what's with this ahjusshi it doesn't suit him to leave an emoticon he's cute i only introduced them to each other i found out later that they were dating each other without me knowing what's with that oh you also set ruby up with her boyfriend i also only introduced ruby to him and they started dating on their own then i should stick by you from now on if i'm going to get married oh right we're catching up and forgot we haven't even given our congratulatory money yet i'm in charge of giving them the envelopes from the marketing team yu ba bi team leader yu can't come so he put me in charge of it ah do you know that he's going to an overseas branch an overseas branch yes he was assigned to singapore he said he couldn't come because he's leaving today so he asked me to bring the envelopes what's this this is ridiculous writer cell ran away and love isn't here is there a cell village without a prime cell reason huh is our yumi really living well right now the wedding was broken off and she's missing the deadline hey you can't be like that today is yi da's wedding ceremony let's not ruin the mood i'm saying that i'm sad everyone else gets married so easily is there anything else no that's everything i just left i'll call you when i get to the airport okay hello this is the caf at the baekseok dong intersection oh yes hello i'm calling the number that was left on the coupon ah yes what is it she's a writer i thought she would be looking for it yes that's right she would be looking for it i'm glad that i had your phone number yes thank you she must be at the wedding right now is it okay to head to the airport now oh yes no wait one moment i've got to stop somewhere this is my first request more than anything else please be considerate of each other in the passion absorbed by each other's charms the other's strengths make you happy are they going to give us steak or galbitang i want to eat steak oppa hm by the way isn't that woman in the pink dress pretty the one on the bride's side you're way prettier ruby what are you saying that's obvious did i say something too obvious hey shh let's listen courteously to the good words yes sir the husband has to love his wife and the wife has to love her husband in order to become a true family alright everyone listen up writer has run away we are in a bind there is no place to retreat to yumi couldn't meet the deadline today and she lost the manuscript for the next three weeks she doesn't even have any idea about her story's ending oh no what should she do all that she has left is a missed deadline malicious comments and the interest on her loan so today's strategy the thirty six strategy thirty six strategems if all else fails retreat is that a strategy thirty six as soon as the ceremony ends yumi will leave the ceremony hall turn her phone off and go to mom's house what and she'll disappear until when until writer comes back and she comes up with a plan that's the only way that writer kim yumi will live today what makes love complete isn't passion oh wait it's ba bi it's ba bi love is yumi how are you you're probably attending the wedding right now i was contacted because you left your laptop at the cafe i came to get it so i could bring it to the wedding but i don't think i can make it because traffic is so backed up what time did you say your flight was i'm leaving for singapore today you see did you doze off last night again are you standing at the end of your path close your eyes and come into my arms everything is all right i can't even express it in words so i'm sorry yumi but i left your laptop in the airport locker i was trying to help you but i ended up inconveniencing you i'm sorry one day i'll hold you tightly in my arms you know that i'm always supporting writer kim yumi right even if we've broken up that won't change i hope you write good stories goodbye i will become the moon just for you so that you can breathe within me darkness and loneliness entirely will cease to exist cause you're my star no matter what kind of night falls i will shine on you so that you can fall asleep in the warmth of the moonlight cause you are my star cause you are my life i'm just shining on your night when i met you like a miracle i got to know love when you cry everything ends for me i'll give you all my light i will become the moon just for you so that you can breathe within me darkness and loneliness entirely will cease to exist cause you're my star yumi oh wung my meeting ended late the ceremony isn't over right the ceremony is over everyone's eating go on and head inside wait where are you going to go find something what my laptop i lost my laptop today's my deadline see you later yumi yumi cause you are my life i'm just shining on your night you can take my car terminal i'm just shining on your night it's locker number you know the passcode right will you end your locker usage and remove your items yes no please wait a moment just a moment please thank you for your use please close the door completely after removing your items too much time has gone by he's probably already on the plane let's at least leave him a text message so he can see it when he gets there departures i found the laptop things must have been hectic and busy thank you for going out of your way huindol village bus stop ba bi i all this time i've been thinking a lot i think i know what you're going to say i had a feeling i'm sorry by the time you see this you'll be in singapore right i hope only good things happen for you there too i'll also sincerely be rooting for you oh what's this yumi oh i thought you got on the plane it was delayed there was no announcement i think it happened so i can see you before i go really i'm glad that i could see you and say goodbye in person before i left you saved me my entire manuscript was in here thank you when will you finish the book the end of the year if it goes well around christmas oh i see finish it well i want to but i'm not skilled enough you'll do well what about a boyfriend did you get a boyfriend no i don't have time to really whats this why is he smiling what does that mean ba bi really makes my heart flutter hey hey are you guys starting up again is this the first or second time knock it off ba bi always speak sweetly we know we know you me do you have a girlfriend i am seeing someone what's this look at that you heard him right get a hold of yourself i know i said i know did i say anything i see i hope it goes well team leader ba bi we have to go in now oh really i'll head in okay have a good trip bye by the way is that woman from earlier your girlfriend oh no for some reason the mood seemed to be a bit she's my ex girlfriend what about now it's been a while since we broke up then why was she at the airport things ended up that way coincidentally it was as if she was a girlfriend coming to see me off right but team leader why won't you go on any blind dates i've recommended several women but you said you weren't going on any because i don't want to why why are you smiling why aren't you going on any i'm not sure i don't really know why either episode the return love disappeared one year ago on christmas eve i didn't hear anything the small light went out dating damn you this damned love affair i'm telling you it's exasperating love changed into the incarnation of rage love give the prime cell position to writer ling ling don't try to be understanding aside from minor quirks i am usually such a person the day that she got kicked out of her position as prime cell love was banished to another dimension even when we met wung as if it were fate and when we got back together with ba bi she didn't come back yumi should we get married let's get married even when she was proposed to all that time i've been thinking about it a lot i think i know what you're going to say even when we were breaking up love didn't come back i'm better at that wait why of course it's not like there was never a time when her heart fluttered after that writer kim ah oppa mr yeon il oh my friend said he wanted to greet you before he left say hello yeon il this is writer yumi hello ah hello i'm really enjoying my love muse thank you it's love love is here she said love is here so she's finally back she sometimes wonders is this possibly a romantic feeling but me i'm not love i'm curiosity there are a lot of cases where it's not it's curiosity it's curiousity what is it why are you acting like that you guys were all fooled so annoying romance customer here is the book you were looking for yes wow he's handsome it must be real this time love has really come back handsome men are not guilty where's love it's not her it's not her it was sensitivity what the heck man i'm pissed off excuse me i think you dropped this ah thank you really really my heart just dropped is it real this time this time it's love guys that guy isn't he so sexy i want to touch his arms just once clean him up at first i could fool my feelings but these days yumi can't be fooled eonni you were piercing a hole with your eyes at z's friends are you falling in love it's not like that that's suspicious i told you that's not what it is okay will love return this christmas no this christmas these guys returned fat fat cells we have finally arrived on a new land this is the land we will be living from now on leader then where do we settle down at let's go to the heart heart heart no let's go to the love handles huh the love handles the love handles are safe if we go there then there is lesser chances to get kicked out on top of that a lot of our fat siblings already live there yay let's go let's go to the paradise of happiness the love handles to the love handles the love handles yay woo no not that way guys come here it's not why can't i figure this out yumi is now trying to meet her deadline before the end of her novel i also wouldn't know my heart i just have to write five chapters just five chapters there's a me why does it have to be five chapters i don't know even if i walk slowly my heart is running far away there why is it so messy reason how about we clean the room before we write wait are you crazy why are you trying to do things you don't normally do during her deadline reason i suddenly want to find out which resorts hollywood celebs go to i really want to know where let's try looking it up curiosity why are you acting like this too my heart is far away there even at night when everyone is asleep it's racing wide awake when you get deadline syndrome everything except the deadline becomes interesting where is this there is a world i don't know even if i spend a day when nothing happens these hairs even i still don't know it's running there far away it shouldn't run so fast even if i knew i can't do anything with my heart this is so fun shall i wash the blankets in the village too stop it i'm going crazy why are the last five chapters so hard i'm even sleepy hello eonni when are you done i don't know i don't have a plan i think i'm going to be cancelled what do you mean cancelled we all got a party together and are waiting for you a party we're waiting to congratulate you for finishing your novel first thing in the morning we're going to start now it's planned for the fifth hurry up and come miss writer the side dishes and beer here are seriously killer hurry up and come eonni yi da said she's coming right after her honeymoon trip too are you going to sit in the corner of your room writing alone on christmas eve eonni do you really want to live like that no so get dressed and hurry up a party that sounds good what i just thought of something if i make the ending happen at a year end party eonni i can't hear you very well ah that's right that's it they meet each other for the first time there coincidentally at the year end party they can't talk to each other at all because the music is so loud what what are you talking about okay i'm hanging up that's right are you paying attention to me they met there for the first time or is it meaningless do our eyes keep meeting or were you just looking at something behind me that day was christmas eve yeon jae ends up going to the year end party thrown by her company and ends up meeting him as if it's fated i'm going to continue to hide it so you won't know how i feel but because the music is too loud she can't hear him when he tells her his name but he remembered yeon jae's name like a miracle when her writer's block suddenly clears it's extremely thrilling it's none other than endorphin time yeah endorphin everyone we're here yay woo everybody shout who are we en dor phin yay woo i remember oh i want to hear your heart the end enter the end send your mail has been sent successfully i've submitted the manuscript it's over it's done it's been a year since she became a writer during that time yumi wrote two novels my love muse and it's sequel it's so refreshing kim yumi you worked hard good job yumi you worked hard yumi you worked hard yumi you worked hard yumi the cell village is also busy at the end of the year after the endorphin concert there's a year end awards ceremony it's a beautiful night yumi awards yumi awards all right then i'll announce this year's award winners end of the year closing the most improved cell award for yumi's cells that showed the most growth this year it can't be any other cell but me why are you acting as if you don't know when you do so embarrassing the best cell award the winner is the winner is let's go to commercials here my love muse currently a best seller yumi awards best cell award sensitivity writer flowy the winner is ba bi's cells yumi awards the best cell award babi's cells huh what i can't believe this seriously as babi's cells are currently employed overseas they can't attend the award ceremony so i will accept in their hey i'm the one who made yumi a writer and i made the first and second books a success you should be giving that award to me what kind of bulls t is this let me go writer calm down you are the one who wrote the books but ba bi was the one who saved you what ba bi saved me that's why i'm asking do you want to write for us i think you'll do a good job the first one to recognize our talent was ba bi the one who always supported us was also ba bi my dear the one who even found our laptop in the end was ba bi too writer cell 

In [14]:
print(data["subtitle"][3])

1
00:00:06,000 --> 00:00:12,074
Watch any video online with Open-SUBTITLES
Free Browser extension: osdb.link/ext

2
00:00:53,650 --> 00:00:56,410
<i>Yumi's Cells 2</i>

3
00:00:59,390 --> 00:01:03,070
<i>Episode 39: Laptop</i>

4
00:01:06,380 --> 00:01:09,540
First place is mine! Mine!

5
00:01:10,500 --> 00:01:14,000
Oh yeah! First place! First place!

6
00:01:14,000 --> 00:01:16,580
The unique sweetness is gone. It's no fun!

7
00:01:16,580 --> 00:01:21,810
Writer Kim Yumi, are you going through a hard
time? This is like a funeral march dragging on.

8
00:01:21,810 --> 00:01:26,410
Why did you make a sequel? Just
end it if you don't have anything to say.

9
00:01:29,790 --> 00:01:32,950
<i>I can't read this anymore. I'm leaving now.</i>

10
00:01:32,950 --> 00:01:34,440
What?

11
00:01:34,440 --> 00:01:38,650
<i>Oh yeah! First place!
The unique sweetness has disappeared.</i>

12
00:01:40,670 --> 00:01:45,960
Everything is malicious comments.

13
00:01:46,990 --> 00:01:52,160
It's because it's so popular. There are
no malicious comments if it's not popular.

14
00:01:53,070 --> 00:01:58,640
But still, there are too many malicious comments these days.

15
00:01:58,640 --> 00:02:03,850
It's because the ending is almost near. They
must be worried that it won't be a happy ending.

16
00:02:09,720 --> 00:02:14,720
Don't worry too much about it, Writer.
You're going to give them a good ending.

17
00:02:15,650 --> 00:02:17,540
A good ending?

18
00:02:17,540 --> 00:02:20,510
Our company's employees are all looking forward to it, too.

19
00:02:20,510 --> 00:02:25,990
Since you're not giving them any hints, they're
all in suspense wondering what the ending will be.

20
00:02:31,050 --> 00:02:36,830
What will the ending be? I'm curious about that,
too! Won't you let me know what the ending will be?!

21
00:02:38,190 --> 00:02:42,050
Cooking cell told me to bring this to you so you can gain some strength.

22
00:02:44,890 --> 00:02:46,780
Bye!

23
00:02:47,560 --> 00:02:50,620
The ending is coming.
<i>God Yumi! Let's have a legendary ending!!</i>

24
00:02:50,620 --> 00:02:56,720
<i>Although you get the full support of everyone once you
become the top priority, it's not necessarily a good thing.</i>

25
00:02:56,720 --> 00:03:00,900
Oh, no. What should she do?

26
00:03:00,900 --> 00:03:03,350
She has to end it well.

27
00:03:03,350 --> 00:03:07,240
What should she do if it doesn't go well?

28
00:03:07,910 --> 00:03:11,900
- What if Yumi can't give a good ending?
- Stop it!

29
00:03:11,900 --> 00:03:13,850
They said they're looking forward to a good ending.

30
00:03:13,850 --> 00:03:19,070
If it's not a good ending, won't Yumi be ostracized?

31
00:03:19,070 --> 00:03:22,420
I said stop it, please!

32
00:03:22,420 --> 00:03:26,850
<i>This cell is always clinging on to the Prime Cell. Anxiety.</i>

33
00:03:26,850 --> 00:03:31,330
If this doesn't go well, it's all over! We
used all the down payment to buy the house.

34
00:03:31,330 --> 00:03:34,130
We got a huge loan!

35
00:03:34,130 --> 00:03:36,930
If things go badly, how will we pay back the loan?

36
00:03:36,930 --> 00:03:42,080
What to do? What will we do? What will we do?!

37
00:03:42,080 --> 00:03:44,890
I said stop it!

38
00:03:45,600 --> 00:03:49,620
I'm so anxious that I can't write!

39
00:04:09,000 --> 00:04:13,130
You'll send me the manuscript tomorrow
morning before the wedding, right?

40
00:04:13,130 --> 00:04:15,990
Ah, I should.

41
00:04:15,990 --> 00:04:18,540
Miss Writer, fighting! I'll see you at the ceremonial hall.

42
00:04:18,540 --> 00:04:21,000
Yes, fighting!

43
00:04:27,750 --> 00:04:32,650
<i>Yumi was already pretty stressed because
she had to finish the manuscript for the sequel.</i>

44
00:04:34,460 --> 00:04:38,900
<i>But the real incident occured the night before Yi Da's wedding.</i>

45
00:04:38,900 --> 00:04:42,590
Reason! Emergency, emergency!

46
00:04:42,590 --> 00:04:45,990
- What is it?
- I don't see the laptop!

47
00:04:45,990 --> 00:04:48,180
Look for it. It must be somewhere.

48
00:04:48,180 --> 00:04:50,430
It's not there!

49
00:04:51,090 --> 00:04:53,090
<i>It's not in the place where she usually charges it?</i>

50
00:04:53,090 --> 00:04:54,980
<i>No, it's not.</i>

51
00:04:54,980 --> 00:04:57,700
<i>Then what about the table?</i>

52
00:05:00,270 --> 00:05:02,330
<i>What about under the bed?</i>

53
00:05:03,510 --> 00:05:05,590
<i>It's not there!</i>

54
00:05:05,590 --> 00:05:08,310
<i>Maybe she put it in another bag before she left?</i>

55
00:05:10,020 --> 00:05:12,020
<i>No!</i>

56
00:05:13,020 --> 00:05:16,630
<i>Did it get mixed in with the recyclables?</i>

57
00:05:16,630 --> 00:05:18,920
<i>I'm telling you it didn't!</i>

58
00:05:23,070 --> 00:05:25,220
It's not here. It's gone.

59
00:05:25,220 --> 00:05:27,700
How much of the manuscript is in the laptop?

60
00:05:27,700 --> 00:05:33,060
Including the episode that I'm going to
upload tomorrow, it's 60 chapters in 6 episodes.

61
00:05:33,060 --> 00:05:36,650
That much?! You didn't make a backup?

62
00:05:39,100 --> 00:05:42,160
She definitely left it somewhere outside before she came home.

63
00:05:42,160 --> 00:05:45,470
What places did she visit today?

64
00:05:53,150 --> 00:05:58,420
<i>It's because the ending is almost near. They
must be worried that it won't be a happy ending.</i>

65
00:05:58,420 --> 00:06:02,260
<i>There! She had the laptop up until then.</i>

66
00:06:09,530 --> 00:06:11,360
Yes, Miss Writer?

67
00:06:12,360 --> 00:06:14,270
- Your laptop?
- Yes.

68
00:06:14,270 --> 00:06:19,750
We were looking at my laptop together
this morning and talking about the comments.

69
00:06:23,080 --> 00:06:25,660
That was my laptop, though.

70
00:06:25,660 --> 00:06:29,250
You didn't take your laptop out.

71
00:06:29,250 --> 00:06:33,290
Did you lose it? <i>How?</i>

72
00:06:33,290 --> 00:06:36,490
Yes, well...

73
00:06:36,490 --> 00:06:39,510
I should look for it. I'll find it.

74
00:06:39,510 --> 00:06:43,520
<i>You backed it up, right? As long as the manuscript is alright...</i>

75
00:06:43,520 --> 00:06:45,960
Oh, of course!

76
00:06:49,000 --> 00:06:50,820
Yes.

77
00:07:00,200 --> 00:07:02,400
She must have really lost it.

78
00:07:02,400 --> 00:07:04,340
Let's not despair!

79
00:07:04,340 --> 00:07:08,770
For now, she can just go buy a new laptop tomorrow and rewrite it all!

80
00:07:10,710 --> 00:07:14,580
Rewrite it all? 60 pages?!

81
00:07:15,350 --> 00:07:18,300
Don't you have the outline in your head?

82
00:07:26,750 --> 00:07:31,890
<i>In the end, Yumi couldn't find the
laptop up to the morning of the wedding.</i>

83
00:07:31,890 --> 00:07:36,280
What will she do now? Everyone from the
publishing company is going to the wedding.

84
00:07:36,280 --> 00:07:40,220
What will she do? What to do? Come up with an excuse.

85
00:07:40,220 --> 00:07:42,210
There's no manuscript to upload today,

86
00:07:42,210 --> 00:07:47,060
and there's no manuscript to upload next week
either. Even if she writes, there are malicious comments.

87
00:07:47,060 --> 00:07:51,690
What do we do? They won't leaveâ

88
00:07:51,690 --> 00:07:53,760
I'm not being the prime cell anymore.

89
00:07:55,330 --> 00:07:57,210
Bye, guys.

90
00:07:58,230 --> 00:08:00,420
Don't look for me ever again!

91
00:08:00,420 --> 00:08:02,850
Goodbye!

92
00:08:02,850 --> 00:08:05,890
- Writer!
- Oh, no!

93
00:08:09,560 --> 00:08:14,830
<i>Writer abandoned her prime cell position and ran away.</i>

94
00:08:27,910 --> 00:08:31,620
<i>Thank you. Thank you.</i>

95
00:08:31,620 --> 00:08:33,490
Thank you.

96
00:08:33,490 --> 00:08:36,050
Aigo, Writer Yumi! You made it?

97
00:08:36,050 --> 00:08:38,060
Editor-in-Chief. Congratulations.

98
00:08:38,060 --> 00:08:39,950
Thank you.

99
00:08:40,650 --> 00:08:45,020
- Where's Yi Da?
- She's in the waiting room right now.

100
00:08:45,020 --> 00:08:47,990
You finished by the deadline before you came, right?

101
00:08:48,880 --> 00:08:51,730
- Yes.
- I'll read it after the ceremony.

102
00:08:51,730 --> 00:08:54,450
I'm looking forward to the last chapter.

103
00:08:54,450 --> 00:08:56,540
Yes.

104
00:08:56,540 --> 00:08:58,000
Oh, yes. Excuse me.

105
00:08:58,000 --> 00:09:00,490
- Congratulations.
- Oh, thank you.

106
00:09:06,590 --> 00:09:09,260
<i>The groom's side</i>

107
00:09:10,730 --> 00:09:12,670
<i>Kim Yumi</i>

108
00:09:18,890 --> 00:09:20,700
Wow, Miss Yumi!

109
00:09:20,700 --> 00:09:22,930
Oh, Bon Hui! Hello!

110
00:09:22,930 --> 00:09:25,820
- It's been a long time. It's been so long!
- I know!

111
00:09:25,820 --> 00:09:27,890
It's good to see you.

112
00:09:27,890 --> 00:09:31,530
Wait, I heard that you're the one who set up the bride and groom.

113
00:09:31,530 --> 00:09:35,200
They said that the groom is your editor-in-chief.

114
00:09:35,200 --> 00:09:38,210
I didn't set them up.

115
00:09:44,740 --> 00:09:47,360
<i>Really? He was a loser this time, too?</i>

116
00:09:47,360 --> 00:09:51,450
<i>Yeah. He was the worst of the worst.</i>

117
00:09:51,450 --> 00:09:54,250
<i>It's not like I'm betting on who's worse.</i>

118
00:09:54,250 --> 00:09:57,790
<i>- Hey, I really got angry andâ
- Miss Writer.</i>

119
00:09:59,080 --> 00:10:01,490
<i>Oh, Editor-in-Chief?</i>

120
00:10:01,490 --> 00:10:04,450
<i>I saw you on my way to the publishing company.</i>

121
00:10:04,450 --> 00:10:07,720
<i>Oh, I had plans with my friend, so...</i>

122
00:10:07,720 --> 00:10:09,670
<i>I was just about to get up and leave anyway.</i>

123
00:10:09,670 --> 00:10:14,350
<i>Yi Da, say hello. This is my
Editor-in-Chief. I talked about him a lot, right?</i>

124
00:10:14,350 --> 00:10:17,360
<i>This is my former co-worker, Yi Da.</i>

125
00:10:17,360 --> 00:10:20,210
<i>Hello, I'm Kang Yi Da.</i>

126
00:10:20,210 --> 00:10:22,580
<i>Hello. I'm Ahn Dae Yong.</i>

127
00:10:22,580 --> 00:10:25,590
<i>- You're the best!
- Pardon?</i>

128
00:10:25,590 --> 00:10:28,460
<i>You're the person that chose our Yumi's work.</i>

129
00:10:28,460 --> 00:10:32,100
<i>I always told Yumi that you've got a great eye..</i>

130
00:10:32,100 --> 00:10:35,320
<i>You've really got an amazing eye for writers.</i>

131
00:10:35,320 --> 00:10:37,080
<i>That's because Miss Writer's writing isâ</i>

132
00:10:37,080 --> 00:10:40,420
<i>You're the best! Really the best!</i>

133
00:10:52,290 --> 00:10:55,420
<i>What is this? Who is that cute creature?</i>

134
00:10:55,420 --> 00:10:58,000
<i>She said she's Kang Yi Da.</i>

135
00:10:58,000 --> 00:11:00,660
<i>Let's save that. Kang Yi Da.
[Kang Yi Da]</i>

136
00:11:00,660 --> 00:11:02,820
<i>Her name is Kang Yi Da.</i>

137
00:11:02,820 --> 00:11:06,380
<i>Cute Best (Jjang) Yi Da.</i>

138
00:11:06,380 --> 00:11:09,040
<i>The line is perfect, too!</i>

139
00:11:09,040 --> 00:11:11,060
<i>- Hello!
- Hello.</i>

140
00:11:15,370 --> 00:11:21,580
<i>Hello, I'm Ahn Dae Yong who greeted
you last time. You remember me, right?</i>

141
00:11:21,580 --> 00:11:24,150
<i>Oh, this ahjusshi?</i>

142
00:11:24,150 --> 00:11:28,200
<i>Yes, of course. Hello, how have you been?</i>

143
00:11:28,200 --> 00:11:32,010
<i>I have a meeting nearby today.</i>

144
00:11:32,010 --> 00:11:36,460
<i>If it's okay with you, shall we have lunch together?</i>

145
00:11:36,460 --> 00:11:39,510
<i>Julie Literature Editor-in-Chief Ahn Dae Yong</i>

146
00:11:40,300 --> 00:11:42,280
<i>Yes, that sounds good.</i>

147
00:11:50,170 --> 00:11:54,670
<i>What's with this ahjusshi? It doesn't suit him to leave an emoticon.</i>

148
00:11:57,510 --> 00:11:59,420
<i>He's cute.</i>

149
00:12:01,250 --> 00:12:05,870
I only introduced them to each other. I found out later
that they were dating each other without me knowing.

150
00:12:05,870 --> 00:12:09,530
What's with that? Oh, you also set Ruby up with her boyfriend.

151
00:12:09,530 --> 00:12:13,630
I also only introduced Ruby to him,
and they started dating on their own.

152
00:12:13,630 --> 00:12:17,190
Then I should stick by you from now on if I'm going to get married.

153
00:12:18,180 --> 00:12:22,310
Oh right! We're catching up and forgot we
haven't even given our congratulatory money yet.

154
00:12:26,650 --> 00:12:29,540
I'm in charge of giving them the envelopes from the marketing team.

155
00:12:32,340 --> 00:12:34,490
<i>Yu Ba Bi</i>

156
00:12:36,230 --> 00:12:40,860
Team Leader Yu can't come, so he put me in charge of it.

157
00:12:40,860 --> 00:12:43,090
Ah...

158
00:12:43,090 --> 00:12:47,550
Do you know that he's going to an overseas branch?

159
00:12:47,550 --> 00:12:52,140
- An overseas branch?
- Yes, he was assigned to Singapore.

160
00:12:52,140 --> 00:12:57,100
He said he couldn't come because he's leaving
today. So he asked me to bring the envelopes.

161
00:13:00,170 --> 00:13:04,610
<i>What's this? This is ridiculous.</i>

162
00:13:04,610 --> 00:13:08,150
Writer Cell ran away, and Love isn't here.

163
00:13:08,150 --> 00:13:11,330
Is there a cell village without a prime cell?

164
00:13:13,060 --> 00:13:15,150
- Reason.
- Huh?

165
00:13:15,150 --> 00:13:19,080
Is our Yumi really living well right now?

166
00:13:20,570 --> 00:13:25,090
The wedding was broken off, and she's missing the deadline.

167
00:13:25,090 --> 00:13:30,920
Hey, you can't be like that. Today is Yi Da's
wedding ceremony. Let's not ruin the mood.

168
00:13:30,920 --> 00:13:35,890
I'm saying that I'm sad. Everyone else gets married so easily.

169
00:13:45,840 --> 00:13:49,520
- Is there anything else?
- No, that's everything.

170
00:13:57,950 --> 00:14:02,600
I just left. I'll call you when I get to the airport.

171
00:14:02,600 --> 00:14:04,190
Okay.

172
00:14:13,770 --> 00:14:15,960
Hello?

173
00:14:15,960 --> 00:14:21,340
<i>- This is the cafÃ© at the Baekseok-dong intersection.
</i>- Oh, yes.

174
00:14:21,340 --> 00:14:23,390
Hello.

175
00:14:23,390 --> 00:14:27,480
I'm calling the number that was left on the coupon.

176
00:14:27,480 --> 00:14:31,080
Ah, yes. What is it?

177
00:14:34,370 --> 00:14:38,690
She's a writer. I thought she would be looking for it.

178
00:14:38,690 --> 00:14:41,900
Yes, that's right. She would be looking for it.

179
00:14:41,900 --> 00:14:45,730
I'm glad that I had your phone number.

180
00:14:45,730 --> 00:14:48,410
Yes, thank you.

181
00:14:55,040 --> 00:14:57,680
She must be at the wedding right now.

182
00:15:06,690 --> 00:15:09,010
Is it okay to head to the airport now?

183
00:15:09,010 --> 00:15:10,780
Oh, yes.

184
00:15:10,780 --> 00:15:15,660
No, wait! One moment. I've got to stop somewhere.

185
00:15:16,670 --> 00:15:18,990
<i>This is my first request.</i>

186
00:15:20,030 --> 00:15:24,320
<i>More than anything else, please be considerate of each other.</i>

187
00:15:24,320 --> 00:15:29,920
In the passion absorbed by each other's charms, the other's strengths

188
00:15:29,920 --> 00:15:32,360
make you happy...

189
00:15:32,360 --> 00:15:35,140
Are they going to give us steak?

190
00:15:35,140 --> 00:15:37,850
Or galbitang?

191
00:15:37,850 --> 00:15:40,230
I want to eat steak.

192
00:15:43,120 --> 00:15:44,790
- Oppa.
- Hm?

193
00:15:44,790 --> 00:15:51,120
By the way, isn't that woman in the pink
dress pretty? The one on the bride's side?

194
00:15:51,120 --> 00:15:55,070
- You're way prettier, Ruby.
- What are you saying? That's obvious.

195
00:15:55,070 --> 00:15:57,880
Did I say something too obvious?

196
00:15:59,260 --> 00:16:01,100
Hey.

197
00:16:01,860 --> 00:16:04,340
Shh.

198
00:16:04,340 --> 00:16:08,280
Let's listen courteously to the good words.

199
00:16:08,280 --> 00:16:11,360
- Yes, sir.
<i>- The husband has to love his wife</i>

200
00:16:11,360 --> 00:16:16,140
<i>and the wife has to love her husband in order to become a true family.</i>

201
00:16:16,140 --> 00:16:19,080
<i>Alright, everyone. Listen up!</i>

202
00:16:19,080 --> 00:16:21,150
Writer has run away.

203
00:16:21,150 --> 00:16:25,480
We are in a bind. There is no place to retreat to.

204
00:16:25,480 --> 00:16:30,650
Yumi couldn't meet the deadline today, and
she lost the manuscript for the next three weeks.

205
00:16:30,650 --> 00:16:33,970
She doesn't even have any idea about her story's ending.

206
00:16:33,970 --> 00:16:36,580
- Oh, no.
- What should she do?

207
00:16:36,580 --> 00:16:41,290
All that she has left is a missed deadline, malicious comments,

208
00:16:41,290 --> 00:16:44,840
and the interest on her loan.

209
00:16:46,050 --> 00:16:49,150
So today's strategy...

210
00:16:55,510 --> 00:16:58,130
the thirty-six strategy!
<i>(Thirty-Six Strategems: "If all else fails, retreat.")</i>

211
00:16:58,130 --> 00:17:00,220
- Is that a strategy?
- Thirty-six?

212
00:17:00,220 --> 00:17:03,210
As soon as the ceremony ends, Yumi will leave the ceremony hall,

213
00:17:03,210 --> 00:17:06,620
turn her phone off, and go to Mom's house.
- What?

214
00:17:06,620 --> 00:17:09,730
And she'll disappear!

215
00:17:10,410 --> 00:17:14,820
Until when? Until Writer comes back and she comes up with a plan!

216
00:17:14,820 --> 00:17:20,050
That's the only way that Writer Kim Yumi will live today!

217
00:17:22,370 --> 00:17:27,000
<i>What makes love complete isn't passion...</i>

218
00:17:27,000 --> 00:17:31,340
<i>Oh, wait! It's Ba Bi. It's Ba Bi!</i>

219
00:17:31,950 --> 00:17:34,040
<i>Love is...</i>

220
00:17:34,040 --> 00:17:36,950
<i>Yumi. How are you?</i>

221
00:17:36,950 --> 00:17:39,870
<i>You're probably attending the wedding right now.</i>

222
00:17:39,870 --> 00:17:43,850
<i>I was contacted because you left your laptop at the cafe.</i>

223
00:17:50,300 --> 00:17:53,440
<i>I came to get it so I could bring it to the wedding,</i>

224
00:17:54,110 --> 00:17:56,850
<i>but I don't think I can make it because traffic is so backed up.</i>

225
00:17:57,770 --> 00:18:00,130
What time did you say your flight was?

226
00:18:00,130 --> 00:18:02,850
<i>I'm leaving for Singapore today, you see.</i>

227
00:18:08,200 --> 00:18:13,400
â« <i>Did you doze off last night again?</i> â«

228
00:18:13,400 --> 00:18:18,790
â« <i>Are you standing at the end of your path?</i> â«

229
00:18:18,790 --> 00:18:23,700
â« <i>Close your eyes and come into my arms</i> â«

230
00:18:23,700 --> 00:18:29,460
â« <i>Everything is all right</i> â«

231
00:18:29,460 --> 00:18:34,560
â« <i>I can't even express it in words</i> â«

232
00:18:34,560 --> 00:18:37,660
<i>So I'm sorry, Yumi,</i>

233
00:18:37,660 --> 00:18:40,410
<i>but I left your laptop in the airport locker.</i>

234
00:18:43,420 --> 00:18:47,690
<i>I was trying to help you, but I ended up inconveniencing you. I'm sorry.</i>

235
00:18:51,130 --> 00:18:53,860
â« <i>One day I'll hold you tightly in my arms</i> â«

236
00:18:53,860 --> 00:18:58,490
<i>You know that I'm always supporting Writer Kim Yumi, right?</i>

237
00:18:59,540 --> 00:19:03,860
<i>Even if we've broken up, that won't change.</i>

238
00:19:04,600 --> 00:19:08,470
<i>I hope you write good stories. Goodbye.</i>

239
00:19:12,290 --> 00:19:17,990
â« <i>I will become the moon just for you</i> â«

240
00:19:17,990 --> 00:19:24,670
â« <i>So that you can breathe within me</i> â«

241
00:19:24,670 --> 00:19:27,290
â« <i>Darkness and loneliness entirely</i> â«

242
00:19:27,290 --> 00:19:29,990
â« <i>will cease to exist</i> â«

243
00:19:29,990 --> 00:19:34,310
â« <i>Cause you're my star</i> â«

244
00:19:34,310 --> 00:19:39,430
â« <i>No matter what kind of night falls, I will shine on you</i> â«

245
00:19:39,430 --> 00:19:46,020
â« <i>so that you can fall asleep in the warmth of the moonlight</i> â«

246
00:19:46,020 --> 00:19:48,840
â« <i>Cause you are my star</i> â«

247
00:19:48,840 --> 00:19:52,560
â« <i>Cause you are my life</i> â«

248
00:19:52,560 --> 00:19:56,920
â« <i>I'm just shining on your night</i> â«

249
00:19:56,920 --> 00:20:03,160
â« <i>When I met you like a miracle</i> â«

250
00:20:03,160 --> 00:20:06,460

In [15]:
data.name.tail(50)

82448    criminal.minds.s12.e16.assistance.is.futile.(2...
82449    criminal.minds.s12.e17.in.the.dark.(2017).eng.1cd
82450    criminal.minds.s12.e18.hells.kitchen.(2017).en...
82451     criminal.minds.s12.e19.true.north.(2017).eng.1cd
82452    criminal.minds.s12.e20.unforgettable.(2017).en...
82453    criminal.minds.s12.e21.green.light.(2017).eng.1cd
82454      criminal.minds.s12.e22.red.light.(2017).eng.1cd
82455                             shit.year.(2010).eng.1cd
82456          stingray.s01.e17.the.big.gun.(1965).eng.1cd
82457    stingray.s01.e18.the.cool.cave.man.(1965).eng.1cd
82458                          house.tricks.(1946).eng.1cd
82459                          house.tricks.(1946).eng.1cd
82460                  service.with.a.guile.(1946).eng.1cd
82461                  service.with.a.guile.(1946).eng.1cd
82462                     klondike.casanova.(1946).eng.1cd
82463                     klondike.casanova.(1946).eng.1cd
82464                      peep.in.the.deep.(1946).eng.1cd
82465                      peep.in.the.deep.(1946).eng.1cd
82466                        rocket.to.mars.(1946).eng.1cd
82467                        rocket.to.mars.(1946).eng.1cd
82468                           rodeo.romeo.(1946).eng.1cd
82469                           rodeo.romeo.(1946).eng.1cd
82470                     the.fistic.mystic.(1946).eng.1cd
82471                     the.fistic.mystic.(1946).eng.1cd
82472                      the.island.fling.(1946).eng.1cd
82473                      the.island.fling.(1946).eng.1cd
82474    vanished.with.beth.holloway.s01.e01.hollowaymc...
82475     qi.s13.e09.messing.with.your.mind.(2015).eng.1cd
82476    vanished.with.beth.holloway.s01.e02.lunsfordgr...
82477    vanished.with.beth.holloway.s01.e03.bradley.(2...
82478    vanished.with.beth.holloway.s01.e04.kessebible...
82479    vanished.with.beth.holloway.s01.e05.figueroadu...
82480    vanished.with.beth.holloway.s01.e06.kopetskyro...
82481    vanished.with.beth.holloway.s01.e07.imbopetron...
82482    vanished.with.beth.holloway.s01.e08.fleischman...
82483    vanished.with.beth.holloway.s01.e09.desirsmart...
82484    vanished.with.beth.holloway.s01.e10.baumhill.(...
82485                      qi.s13.e10.meals.(2016).eng.1cd
82486                         eiga.yurukyan.(2022).eng.1cd
82487    the.count.of.monte.cristo.s01.e03.the.abbe.far...
82488                                la.mer.(2022).eng.1cd
82489                           the.fearway.(2023).eng.1cd
82490                             immanence.(2022).eng.1cd
82491                 star.trek.generations.(1994).eng.1cd
82492                star.trek.insurrection.(1998).eng.1cd
82493                     the.prophets.game.(2000).eng.1cd
82494                           west.beirut.(1998).eng.1cd
82495           frankenstein.the.true.story.(1973).eng.1cd
82496           frankenstein.the.true.story.(1973).eng.1cd
82497                zombie.island.massacre.(1984).eng.1cd
Name: name, dtype: str

### Cleaning Name

In [21]:
def clean_name(name):

    name = name.lower()

    # extract year
    year_match = re.search(r'\((\d{4})\)', name)
    year = year_match.group(1) if year_match else ""

    # extract season
    season_match = re.search(r's\d+', name)
    season = season_match.group(0) if season_match else ""

    # extract episode
    episode_match = re.search(r'e\d+', name)
    episode = episode_match.group(0) if episode_match else ""

    # remove unwanted parts
    name = re.sub(r'\(\d{4}\)', '', name)      # remove (year)
    name = re.sub(r'eng', '', name)            # remove eng
    name = re.sub(r'\d+cd', '', name)          # remove 1cd
    name = re.sub(r's\d+.*', '', name)         # remove everything after season
    name = name.replace('.', ' ')              # replace dots

    # remove extra spaces
    name = re.sub(r'\s+', ' ', name).strip()

    # rebuild clean name
    clean = f"{name} {season} {episode} {year}"
    clean = re.sub(r'\s+', ' ', clean).strip()

    return clean

In [22]:
data["clean_name"] = data["name"].apply(clean_name)

In [25]:
data.clean_name.head(20)

0                         the message 1976
1        here comes the grump s01 e09 1969
2                 yumis cells s02 e13 2022
3                 yumis cells s02 e14 2022
4                              broker 2022
5                            the myth 2005
6                    the great beauty 2013
7        rudrabinar obhishaap s02 e01 2022
8        rudrabinar obhishaap s02 e02 2022
9        rudrabinar obhishaap s02 e03 2022
10       rudrabinar obhishaap s02 e04 2022
11       rudrabinar obhishaap s02 e05 2022
12       rudrabinar obhishaap s02 e06 2022
13       rudrabinar obhishaap s02 e07 2022
14       rudrabinar obhishaap s02 e08 2022
15           alchemy of souls s01 e12 2022
16    parallel world pharmacy s01 e03 2022
17                     trying s02 e01 2021
18                     trying s02 e02 2021
19                     trying s02 e03 2021
Name: clean_name, dtype: str

### Chunking the data

In [ ]:
# !pip install langchain
!pip install langchain-text-splitters

In [26]:
from langchain_text_splitters  import RecursiveCharacterTextSplitter
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200
)

c:\Users\pumas\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [31]:
all_chunks = []

for idx, row in data.iterrows():

    subtitle_id = row["num"]        # subtitle id
    name = row["clean_name"]              # movie / show name
    text = row["clean_text"]        # cleaned subtitle

    # skip very small subtitles
    if len(text) < 200:
        continue

    chunks = text_splitter.split_text(text)

    for chunk in chunks:
        all_chunks.append({
            "subtitle_id": subtitle_id,
            "name": name,
            "text": chunk
        })

    if idx % 1000 == 0:
        print("Processed subtitles:", idx)

Processed subtitles: 0
Processed subtitles: 1000
Processed subtitles: 2000
Processed subtitles: 3000
Processed subtitles: 4000
Processed subtitles: 5000
Processed subtitles: 6000
Processed subtitles: 7000
Processed subtitles: 8000
Processed subtitles: 9000
Processed subtitles: 10000
Processed subtitles: 11000
Processed subtitles: 12000
Processed subtitles: 13000
Processed subtitles: 14000
Processed subtitles: 15000
Processed subtitles: 16000
Processed subtitles: 17000
Processed subtitles: 18000
Processed subtitles: 19000
Processed subtitles: 20000
Processed subtitles: 21000
Processed subtitles: 22000
Processed subtitles: 23000
Processed subtitles: 24000
Processed subtitles: 25000
Processed subtitles: 26000
Processed subtitles: 27000
Processed subtitles: 28000
Processed subtitles: 29000
Processed subtitles: 30000
Processed subtitles: 31000
Processed subtitles: 32000
Processed subtitles: 33000
Processed subtitles: 34000
Processed subtitles: 35000
Processed subtitles: 36000
Processed subtitles: 37000
Processed subtitles: 38000
Processed subtitles: 39000
Processed subtitles: 40000
Processed subtitles: 41000
Processed subtitles: 42000
Processed subtitles: 43000
Processed subtitles: 44000
Processed subtitles: 45000
Processed subtitles: 46000
Processed subtitles: 47000
Processed subtitles: 48000
Processed subtitles: 49000
Processed subtitles: 50000
Processed subtitles: 51000
Processed subtitles: 52000
Processed subtitles: 53000
Processed subtitles: 54000
Processed subtitles: 55000
Processed subtitles: 56000
Processed subtitles: 57000
Processed subtitles: 58000
Processed subtitles: 59000
Processed subtitles: 60000
Processed subtitles: 61000
Processed subtitles: 62000
Processed subtitles: 63000
Processed subtitles: 64000
Processed subtitles: 65000
Processed subtitles: 66000
Processed subtitles: 67000
Processed subtitles: 68000
Processed subtitles: 69000
Processed subtitles: 70000
Processed subtitles: 71000
Processed subtitles: 72000
Processed subtitles: 73000
Processed subtitles: 74000
Processed subtitles: 75000
Processed subtitles: 76000
Processed subtitles: 77000
Processed subtitles: 78000
Processed subtitles: 79000
Processed subtitles: 80000
Processed subtitles: 81000
Processed subtitles: 82000

In [32]:
chunked_data = pd.DataFrame(all_chunks)

In [33]:
print(chunked_data.shape)
chunked_data.head()

(2727690, 3)

,subtitle_id,name,text
0,9180533,the message 1976,in the name of god the most gracious the most ...
1,9180533,the message 1976,the university of al azhar in cairo the high i...
2,9180533,the message 1976,than different gods mecca in a d bilal have yo...
3,9180533,the message 1976,kin where wines and cakes abound the skills of...
4,9180533,the message 1976,hubal who starts our caravans and predicts our...

In [40]:
chunked_data.to_csv(
    "subtitle_chunks.csv",
    index=False
)

In [1]:
import pandas as pd
chunked_data=pd.read_csv('subtitle_chunks.csv')

In [8]:
chunked_data['name'].unique()

<StringArray>
[                        'the message 1976',
        'here comes the grump s01 e09 1969',
                 'yumis cells s02 e13 2022',
                 'yumis cells s02 e14 2022',
                              'broker 2022',
                            'the myth 2005',
                    'the great beauty 2013',
        'rudrabinar obhishaap s02 e01 2022',
        'rudrabinar obhishaap s02 e02 2022',
        'rudrabinar obhishaap s02 e03 2022',
 ...
 'vanished with beth holloway s01 e09 2011',
 'vanished with beth holloway s01 e10 2011',
                          'qi s13 e10 2016',
   'the count of monte cristo s01 e03 1964',
                              'la mer 2022',
                           'immanence 2022',
                   'the prophets game 2000',
                         'west beirut 1998',
         'frankenstein the true story 1973',
              'zombie island massacre 1984']
Length: 51869, dtype: str

In [ ]:
chunked_data[chunked_data['name']==']

Empty DataFrame
Columns: [subtitle_id, name, text]
Index: []

### Embedding with SentenceTransformers

In [ ]:
!pip install sentence-transformers

In [ ]:
# Batch wise Embedding
import numpy as np

from sentence_transformers import SentenceTransformer

all_texts = chunked_data['text'].tolist()

model = SentenceTransformer('all-MiniLM-L6-v2')

batch_size = 300000  # adjusting depending on RAM/GPU

for i in range(0, len(all_texts), batch_size):
    batch_texts = all_texts[i:i+batch_size]
    batch_embeddings = model.encode(batch_texts, show_progress_bar=True)
    
    # Save batch to Kaggle working directory
    batch_file = f"/Embeddings/emb_batch_{i}.npy"
    np.save(batch_file, batch_embeddings)
    
    print(f"Saved batch {i} → {batch_file}")

### Inserting Vectors into ChromaDB

In [ ]:
pip install chromadb

In [ ]:
import chromadb
import numpy as np
import pandas as pd
from tqdm import tqdm

chunked_data = pd.read_csv("subtitle_chunks.csv")

client = chromadb.PersistentClient(path="movie_chroma_db")

collection = client.get_or_create_collection(name="movie_subtitles")

batch_size = 300000 # per batch size
insert_batch = 1000  #Limit to insert vectors in one go is 5200

for i in tqdm(range(0, len(chunked_data), batch_size)):

    emb_file = f"Embeddings/emb_batch_{i}.npy"
    embeddings = np.load(emb_file)

    batch_df = chunked_data.iloc[i:i+batch_size]

    texts = batch_df["text"].tolist()

    metadata = [
        {"subtitle_id": int(row.subtitle_id), "name": row.name}
        for row in batch_df.itertuples()
    ]

    ids = [str(j) for j in range(i, i + len(batch_df))]

    for j in range(0, len(texts), insert_batch):

        collection.add(
            embeddings=embeddings[j:j+insert_batch].tolist(),
            documents=texts[j:j+insert_batch],
            metadatas=metadata[j:j+insert_batch],
            ids=ids[j:j+insert_batch]
        )

    print(f"Inserted embedding batch {i}")

 10%|█         | 1/10 [14:03<2:06:33, 843.76s/it]

Inserted embedding batch 0

 20%|██        | 2/10 [37:38<2:37:18, 1179.87s/it]

Inserted embedding batch 300000

 30%|███       | 3/10 [1:10:36<3:00:09, 1544.24s/it]

Inserted embedding batch 600000

 40%|████      | 4/10 [1:51:04<3:09:19, 1893.20s/it]

Inserted embedding batch 900000

 50%|█████     | 5/10 [2:35:58<3:01:49, 2181.91s/it]

Inserted embedding batch 1200000

 60%|██████    | 6/10 [3:26:05<2:44:09, 2462.37s/it]

Inserted embedding batch 1500000

 70%|███████   | 7/10 [4:29:11<2:24:45, 2895.18s/it]

Inserted embedding batch 1800000

 80%|████████  | 8/10 [5:50:53<1:57:48, 3534.05s/it]

Inserted embedding batch 2100000

 90%|█████████ | 9/10 [7:13:19<1:06:15, 3975.44s/it]

Inserted embedding batch 2400000

100%|██████████| 10/10 [7:20:51<00:00, 2645.17s/it]

Inserted embedding batch 2700000

### Connect to Chroma DB

In [1]:
import chromadb

client = chromadb.PersistentClient(path="movie_chroma_db")

collection = client.get_collection(name="movie_subtitles")

print(collection)

Collection(name=movie_subtitles)

In [2]:
print("Total vectors stored:", collection.count())

Total vectors stored: 2727690

In [ ]:
print(collection.peek(limit=1))

### Input for the System

In [ ]:
import numpy as np
from sentence_transformers import SentenceTransformer

# Load Model
print("Loading embedding model...")
model = SentenceTransformer("all-MiniLM-L6-v2")
print("Model loaded successfully.")


# Preprocess Query
def preprocess(text: str):
    return text.strip().lower()


# Rerank Documents
def rerank(query_embedding, documents, embeddings=None, final_k=5, threshold=0.40):

    if embeddings is None:
        print("Encoding retrieved documents...")
        doc_embeddings = model.encode(documents, normalize_embeddings=True)
    else:
        print("Using embeddings returned by ChromaDB")
        doc_embeddings = np.array(embeddings)

    # cosine similarity
    scores = np.dot(doc_embeddings, query_embedding)

    # sort scores
    sorted_idx = np.argsort(scores)[::-1]

    # filter by threshold
    filtered_idx = [i for i in sorted_idx if scores[i] >= threshold]

    # take top k
    ranked_idx = filtered_idx[:final_k]

    return ranked_idx, scores


# Display Results
def display_results(docs, metas, ranked_idx, scores):

    if not ranked_idx:
        print("\nNo results passed the similarity threshold.")
        return

    print("\nTop Matching Dialogues\n")

    for rank, i in enumerate(ranked_idx, 1):

        movie = metas[i].get("name", "Unknown")
        subtitle_id = metas[i].get("subtitle_id", "N/A")
        score = round(float(scores[i]), 4)

        print(f"Rank        : {rank}")
        print(f"Movie       : {movie}")
        print(f"Subtitle ID : {subtitle_id}")
        print(f"Score       : {score}")
        print(f"Dialogue    : {docs[i][:300]}")
        print("-" * 60)


# Search Function
def search_movie_dialogue(collection, retrieve_k=100, final_k=5, threshold=0.55):

    print("\n--- Movie Dialogue Search ---")

    query = input("Enter movie dialogue or scene: ")

    if not query.strip():
        print("Query cannot be empty.")
        return

    print("\nProcessing query...")

    query = preprocess(query)
    query_embedding = model.encode(query, normalize_embeddings=True)

    print(f"Retrieving top {retrieve_k} documents from database...")

    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=retrieve_k,
        include=["documents", "metadatas", "embeddings"]
    )

    docs = results.get("documents", [[]])[0]
    metas = results.get("metadatas", [[]])[0]
    embeddings = results.get("embeddings", [[]])[0]

    if not docs:
        print("No results found.")
        return

    ranked_idx, scores = rerank(
        query_embedding,
        docs,
        embeddings=embeddings,
        final_k=final_k,
        threshold=threshold
    )

    display_results(docs, metas, ranked_idx, scores)

    return query, docs, metas, ranked_idx

In [59]:
query, docs, metas, ranked_idx = search_movie_dialogue(collection)

--- Movie Dialogue Search ---

Processing query...
Retrieving top 100 documents from database...
Using embeddings returned by ChromaDB

Top Matching Dialogues

Rank        : 1
Movie       : pretty hard cases s02 e10 2022
Subtitle ID : 9384468
Score       : 0.6855
Dialogue    : terminal michaels is so far up my ass right now if i do anything to interfere with the investigation anything he will take me off it or worse i get suspended and then what good am i she'd know where you stood that's how good you'd be look i told you everything i know am i free to go absolutely we wo
------------------------------------------------------------
Rank        : 2
Movie       : nikita s03 e06 2012
Subtitle ID : 9188543
Score       : 0.6078
Dialogue    : okay okay just try and isolate the terminal they're sending from rerouted multiple times son of a bitch how does he keep doing this how do you know it's a he okay daughter of a bitch whoever it is they're in the building right now i gotta tell nikki you keep trying to trace the source terminal engin
------------------------------------------------------------
Rank        : 3
Movie       : the mentalist s02 e06 2009
Subtitle ID : 9280736
Score       : 0.601
Dialogue    : located during an electronic sweep of our offices that's the dedicated receiver to the unit which i found in jane's desk is this true jane you were spying on bosco and his team spying is such an ugly word more just keeping a friendly eye on things did you know about this i would have never allowed t
------------------------------------------------------------
Rank        : 4
Movie       : ncis s13 e05 2015
Subtitle ID : 9232976
Score       : 0.5878
Dialogue    : once for chaining herself to a logging truck in the amazon jungle that's our girl she's like abby unleashed how did you know janice was involved okay i first suspected it when i got into the server room and i traced the fake ebola alert back to her computer but i was sure when the bad guy pronounced
------------------------------------------------------------
Rank        : 5
Movie       : scorpion s04 e05 2017
Subtitle ID : 9279482
Score       : 0.581
Dialogue    : that you've been suspended for being charged with felonious conduct not good yeah i told you she normally says that we will be relieving you of this password to your company's server why do you need it i ordered my staff to delete all data they're doing it as we speak i want my team to watch your te
------------------------------------------------------------

### Using Gemini

In [ ]:
! pip install langchain-google-genai

In [3]:
key='AIzaSyADetfeslrmsaS52LnwstEekmfzKB5J-5A'

In [4]:
from langchain_google_genai import ChatGoogleGenerativeAI
chat_model=ChatGoogleGenerativeAI(api_key=key,model='gemini-2.5-flash')

#### Defining Prompt

In [17]:
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder

prompt = [
    ("system",
     "You are a movie dialogue assistant. "
     "Use ONLY the provided context to answer the question. "
     "Explain properly what is happening the given scene"
     "If the context does not contain the answer, say you do not know."
     "If the user query does not match the context, say do you mean 'the context' and explain the context"),

    MessagesPlaceholder(variable_name="chat_history"),

    ("human",
     "Context:\n{context}\n\n"
     "Question:\n{user_input}\n\n"
     "Answer the question clearly and mention the movie if possible.")
]

prompt_temp = ChatPromptTemplate.from_messages(prompt)

#### Output Parser

In [6]:
from langchain_core.output_parsers import StrOutputParser
output_parser=StrOutputParser()

#### History

In [7]:
from langchain_core.chat_history import InMemoryChatMessageHistory
from langchain_core.runnables.history import RunnableWithMessageHistory
memory={}
def get_session_history(session_id: str):
    if session_id not in memory:
        memory[session_id] = InMemoryChatMessageHistory()
    return memory[session_id]

#### Chain

In [8]:
base_chain = prompt_temp | chat_model | output_parser

chain = RunnableWithMessageHistory(
    base_chain,
    get_session_history,
    input_messages_key="user_input",
    history_messages_key="chat_history",
)

### Pipeline

In [9]:
def rag_pipeline(collection):

    context = []

    print('Searching movie through our Database....................')

    result = search_movie_dialogue(collection)

    if result is None:
        return

    query, docs, metas, ranked_idx = result

    print('Building Context for LLM....................')

    for rank, i in enumerate(ranked_idx, 1):

        movie = metas[i].get("name", "Unknown")
        dialogue = docs[i]

        context.append(
            f"""Document {rank}
            Movie: {movie}
            Dialogue: {dialogue}
            """
                    )

    context_text = "\n".join(context)

    response = chain.invoke(
        {
            "user_input": query,
            "context": context_text
        },
        config={"configurable": {"session_id": "user1"}}
    )

    print("\nAnswer:\n")
    print(response)

In [19]:
rag_pipeline(collection)

Searching movie through our Database....................

--- Movie Dialogue Search ---

Processing query...
Retrieving top 100 documents from database...
Using embeddings returned by ChromaDB

Top Matching Dialogues

Rank        : 1
Movie       : the 40yearold virgin 2005
Subtitle ID : 9185326
Score       : 0.6929
Dialogue    : cute no that tasted good that tasted like shellfish look out sorry watch it exclaiming do you think i'm pretty oh yes oh god yes you're not looking at me yes you're pretty you're not looking at me yes you're pretty do you think i'm pretty look at me look at me i'm looking you're pretty god i just wa
------------------------------------------------------------
Rank        : 2
Movie       : horse camp 2016
Subtitle ID : 9491544
Score       : 0.6233
Dialogue    : hey princess what are you doing i'm ugly you you couldn't be ugly if you tried yes i am look at me i am looking at you sweetheart and you are beautiful no i'm not honey it's what's inside that really counts all those popular girls they're the ugly ones you are the most beautiful girl in the whole wo
------------------------------------------------------------
Rank        : 3
Movie       : uncontrollably fond s01 e20 2016
Subtitle ID : 9380858
Score       : 0.6111
Dialogue    : myself you're the only one who says i'm not pretty i'm so cool looking it's such a waste to show you only hey why are you taking it so suddenly you look really tired i know today i really feel very tired lean on me and sleep if i fall asleep you'll wake me up again i won't wake you up so just sleep
------------------------------------------------------------
Rank        : 4
Movie       : fukeba tobuyona otokodaga 1968
Subtitle ID : 9390280
Score       : 0.604
Dialogue    : thank you sweetie why don't you come in and enjoy a nice hot bath welcome a customer welcome oh it's mr glasses from last night so i was here last night thanks for everything i had a paper bag with me did you happen to see it with the name of a school on it about this big oh yeah it's around here so
------------------------------------------------------------
Rank        : 5
Movie       : alchemy of souls s01 e17 2022
Subtitle ID : 9213946
Score       : 0.6036
Dialogue    : that i will doll you up look at you you look stunning it looks like i am all dolled up now now it is your turn look at how pretty you look mu deok how childish of you i thought you only liked my eyes i know right i only thought your eyes were pretty but your poison must have done a number on me now
------------------------------------------------------------
Building Context for LLM....................

Answer:

This dialogue is from the movie **The 40-Year-Old Virgin (2005)**.

In this scene:
A character is appreciating the taste of something, describing it as "shellfish." This is immediately followed by an exclamation of "look out" and "watch it," suggesting a sudden, possibly dangerous, event or distraction. Amidst this, one character repeatedly seeks reassurance from another, asking "do you think I'm pretty?" and accusing the other of not looking at them, while the other person tries to affirm their prettiness. The character seeking reassurance expresses significant emotional distress, stating they are "in a bad mood," "so tired," and hoping to get their period soon. The scene culminates abruptly with the sound of "glass shattering" and an exclamation of "oh god," indicating a sudden and startling incident.